Repository boostcampwm-2022/Web04-Fitory, pull requests merged in 2022-11, with the labels that each got.

#2 #1 개발 환경 세팅
  .gitignore
  .prettierrc
  README.md
  client/.eslintrc.json
  client/.stylelintrc.json
  client/package.json
  client/tsconfig.json
  client/webpack.common.js
  client/webpack.dev.js
  client/webpack.prod.js
  server/.eslintignore
  server/.eslintrc.json
  server/package.json
  server/tsconfig.json
Labels: 📃 documentation, ⚙ setting

#3 [FE] 코어 - 개발 환경 수정
  .prettierrc
  client/.babelrc
  client/.eslintrc.json
  client/.stylelintrc.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/index.tsx
  client/tsconfig.json
  client/webpack.common.js
  client/webpack.dev.js
  client/webpack.prod.js
Labels: ⚙ setting, 🛶 frontend, ♻ refactor

#5 [BE] 코어 - 개발 환경 수정
  server/.eslintignore
  server/.eslintrc.json
  server/package-lock.json
  server/package.json
  server/tsconfig.json
Labels: ⚙ setting, 🚀 backend, ♻ refactor

#9 [FE] 코어 - 개발 환경 설정 - Yarn Berry
  .gitignore
  client/.pnp.cjs
  client/.pnp.loader.mjs
  client/.vscode/extensions.json
  client/.vscode/settings.json
  client/.yarnrc.yml
  client/README.md
  client/package-lock.json
  client/package.json
  client/yarn.lock
Labels: ⚙ setting, 🛶 frontend

#14 [FE] 코어 - 스타일 설정 - styled components의 theme 설정
  client/src/styles/Theme.ts
Labels: 🎨 style, 🛶 frontend

#22 [BE] - 코어 - 개발 환경 설정 - eslint 수정
  server/.eslintrc.json
Labels: ⚙ setting, 🚀 backend, ♻ refactor

#26 [FE] 코어 - 개발 환경 설정 - 스타일 설정
  client/.pnp.cjs
  client/package.json
  client/src/App.tsx
  client/src/index.tsx
  client/src/styles/GlobalStyle.ts
  client/src/styles/Theme.ts
  client/yarn.lock
Labels: ⚙ setting, 🎨 style, 🛶 frontend

#27 [FE] 코어 - 개발 환경 설정 - storybook, 개발 환경에 맞는 스토리북 세팅 변경
  client/.storybook/preview.js
  client/src/components/BottomNavigationBar/BottomNavigationBar.stories.tsx
  client/src/components/BottomNavigationBar/index.tsx
  client/src/components/BottomNavigationBar/style.ts
Labels: ⚙ setting, 🛶 frontend

#34 [FE] 코어 - 공통 레이아웃 - Path alias, storybook path alias 세팅
  client/.storybook/main.js
  client/tsconfig.json
Labels: ⚙ setting, 🛶 frontend

#38 [FE] 코어 - 개발 환경 설정 - eslintrc 설정 추가
  client/.eslintrc.json
Labels: ⚙ setting, 🛶 frontend, ♻ refactor

#40 [FE] 코어 - 개발 환경 설정 - 린트 수정
  client/.eslintrc.json
  client/src/App.tsx
Labels: ⚙ setting, 🛶 frontend, ♻ refactor

#42 [FE] 코어 - 공통 레이아웃 - 상단 네비게이션바
  .eslintignore
  client/package-lock.json
  client/package.json
  client/public/icons/btn_arrow_left.svg
  client/public/icons/logo.svg
  client/src/components/BackButton/index.tsx
  client/src/components/BackButton/style.ts
  client/src/components/TopNavigationBar/index.tsx
  client/src/components/TopNavigationBar/style.ts
  client/src/stories/TopNavigationBar.stories.tsx
  client/src/styles/Theme.ts
  client/src/types/svg.d.ts
Labels: 🎨 style, ✨ feature, 🛶 frontend

#41 [FE] 코어 - 공통 레이아웃 - 하단 네비게이션바 생성
  client/.eslintrc.json
  client/.idea/client.iml
  client/.idea/inspectionProfiles/Project_Default.xml
  client/.idea/jsLinters/eslint.xml
  client/.idea/modules.xml
  client/.idea/prettier.xml
  client/.idea/vcs.xml
  client/.idea/workspace.xml
  client/.storybook/main.js
  client/package-lock.json
  client/public/icons/btn_home.svg
  client/public/icons/btn_profile.svg
  client/public/icons/btn_search.svg
  client/public/icons/btn_statics.svg
  client/src/components/BottomNavigationBar/BottomNavigationBar.stories.tsx
  client/src/components/BottomNavigationBar/index.tsx
  client/src/components/BottomNavigationBar/style.ts
  client/src/stories/BottomNavigationBar.stories.tsx
  client/src/styles/Theme.ts
Labels: 🎨 style, ✨ feature, 🛶 frontend

#44 [FE] 코어 - 공통 레이아웃 - 하단 네비게이션바 코드 리팩토링
  client/src/components/BottomNavigationBar/index.tsx
Labels: 🛶 frontend, ♻ refactor

#50 [BE] 코어 - 개발 환경 설정 - Github Action 자동 배포 설정
  .github/workflows/deplol.yml
Labels: ⚙ setting, 🚀 backend

#48 [FE] 코어 - 공통 레이아웃 - 하단 네비게이션바 기능 추가 & 리팩토링
  client/.storybook/main.js
  client/src/components/BottomNavigationBar/index.tsx
  client/src/components/BottomNavigationButton/index.tsx
  client/src/components/BottomNavigationButton/style.ts
Labels: ⚙ setting, ✨ feature, 🛶 frontend, ♻ refactor

#54 [BE] 코어 - 개발 환경 서정 - nestjs에 적합하게 gitignore, eslint tsconfig 설정 수정
  .gitignore
  server/.eslintrc.json
  server/tsconfig.json
Labels: ⚙ setting, 🚀 backend, ♻ refactor

#58 [FE] 코어 - 공통 레이아웃 - 하단 네비게이션바
  client/src/components/BottomNavigationBar/style.ts
Labels: 🎨 style, 🛶 frontend

#59 [FE] 코어 - 공통 레이아웃 - 하단 네비게이션바
  client/src/components/BottomNavigationBar/style.ts
Labels: 🎨 style, 🛶 frontend, ♻ refactor

#63 [BE] API 구현 - Google Login API 구현, Google Login 정보 DB에 저장
  server/src/app.module.ts
  server/src/main.ts
  server/src/oauth/google-oauth/dto/create-google-oauth.dto.ts
  server/src/oauth/google-oauth/dto/update-google-oauth.dto.ts
  server/src/oauth/google-oauth/google-oauth.controller.spec.ts
  server/src/oauth/google-oauth/google-oauth.controller.ts
  server/src/oauth/google-oauth/google-oauth.module.ts
  server/src/oauth/google-oauth/google-oauth.service.spec.ts
  server/src/oauth/google-oauth/google-oauth.service.ts
  server/src/oauth/google-oauth/utils/google.guards.ts
  server/src/oauth/google-oauth/utils/google.serializer.ts
  server/src/oauth/google-oauth/utils/google.strategy.ts
  server/src/typeorm/entities/User.ts
  server/src/types/request.type.ts
  server/src/types/user.type.ts
Labels: ✨ feature, 🚀 backend

#68 [BE] 코어 - 개발 환경 설정 - eslint, package.json
  server/.eslintrc.json
  server/package-lock.json
  server/package.json
Labels: ⚙ setting, 🚀 backend

#69 [BE] API 구현 - USER API - 데모를 위한 기초 구현
  server/src/exception/HttpError.ts
  server/src/exception/HttpExceptionFilter.ts
  server/src/user/dto/create-user.dto.ts
  server/src/user/dto/user-login.dto.ts
  server/src/user/user.controller.spec.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.spec.ts
  server/src/user/user.service.ts
Labels: ✨ feature, 🚀 backend

#55 [FE] 코어 - 공통 레이아웃 - 프로필 이미지 컨테이너
  client/public/images/img_default_profile.svg
  client/public/images/img_editable_profile.svg
  client/src/components/ProfileImageContainer/index.tsx
  client/src/components/ProfileImageContainer/style.ts
  client/src/stories/ProfileImageContainer.stories.tsx
Labels: 🎨 style, ✨ feature, 🛶 frontend, 🧪 test

#74 [FE] 코어 - 공통 레이아웃 - 잔디 (Calendar Heatmap)
  client/.eslintrc.json
  client/.storybook/main.js
  client/package.json
  client/src/components/CalendarHeatMap/index.tsx
  client/src/components/CalendarHeatMap/style.ts
  client/src/constants/consts.ts
  client/src/constants/enums.ts
  client/src/stories/CalendarHeatMap.stories.tsx
  client/src/utils/getCalendarHeatMapArray.ts
  client/src/utils/getExerciseStateForOneYear.ts
  client/src/utils/getNumberOfDaysPerMonth.ts
  client/src/utils/test/getExerciseStateForOneYear.spec.ts
  client/tsconfig.json
  client/webpack.common.js
  client/webpack.dev.js
Labels: 🎨 style, ✨ feature, 🛶 frontend, 🧪 test

#81 [BE] DB - TypeORM - TypeORM Entity 세팅
  server/package.json
  server/src/alarms/alarms.controller.ts
  server/src/alarms/alarms.module.ts
  server/src/alarms/alarms.service.ts
  server/src/alarms/entities/alram.entity.ts
  server/src/app.module.ts
  server/src/config/typeorm.config.ts
  server/src/exercises/entities/exercise.entity.ts
  server/src/exercises/exercises.controller.ts
  server/src/exercises/exercises.module.ts
  server/src/exercises/exercises.service.ts
  server/src/follows/entities/follow.entity.ts
  server/src/follows/follows.controller.ts
  server/src/follows/follows.module.ts
  server/src/follows/follows.service.ts
  server/src/oauth/google-oauth/google-oauth.module.ts
  server/src/oauth/google-oauth/google-oauth.service.ts
  server/src/oauth/google-oauth/utils/google.serializer.ts
  server/src/routines/entities/routine.entity.ts
  server/src/routines/routines.controller.ts
  server/src/routines/routines.module.ts
  server/src/routines/routines.service.ts
  server/src/sbd_records/entities/sbd_record.entity.ts
  server/src/sbd_records/sbd_records.controller.ts
  server/src/sbd_records/sbd_records.module.ts
  server/src/sbd_records/sbd_records.service.ts
  server/src/sbd_statistics/entities/sbd_statistics.entity.ts
  server/src/sbd_statistics/sbd_statistics.controller.ts
  server/src/sbd_statistics/sbd_statistics.module.ts
  server/src/sbd_statistics/sbd_statistics.service.ts
  server/src/typeorm/entities/User.ts
  server/src/user/dto/create-user.dto.ts
  server/src/user/dto/user-login.dto.ts
  server/src/user/user.controller.spec.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.spec.ts
  server/src/user/user.service.ts
  server/src/users/entities/user.entity.ts
  server/src/users/users.controller.ts
  server/src/users/users.module.ts
  server/src/users/users.service.ts
  server/src/utils/env.ts
Labels: ✨ feature, 🚀 backend

#83 [BE] API 구현 - 세팅 - swagger 세팅
  server/package-lock.json
  server/package.json
  server/src/main.ts
Labels: ⚙ setting, 🚀 backend

#84 [FE] 코어 - 공통 레이아웃 - 카드 스크롤러 디자인
  client/src/components/CalendarHeatMap/index.tsx
  client/src/components/CalendarHeatMap/style.ts
  client/src/components/design/CardsScroller/index.tsx
  client/src/components/design/CardsScroller/style.ts
  client/src/components/design/Paper/index.tsx
  client/src/components/design/Paper/style.ts
  client/src/stories/CardsScroller.stories.tsx
  client/src/stories/Paper.stories.tsx
Labels: 🎨 style, ✨ feature, 🛶 frontend

#85 [BE] API 구현 - EXERCISE API - Every Exercise History API, Month Exercise History API 구현
  server/src/exercises/dto/every-date.dto.ts
  server/src/exercises/dto/history-of-month.dto.ts
  server/src/exercises/exercises.controller.ts
  server/src/exercises/exercises.service.ts
Labels: ✨ feature, 🚀 backend

#87 [FE] 홈 페이지 - 메인 - 레이아웃 구성
  client/src/App.tsx
  client/src/components/BottomNavigationBar/index.tsx
  client/src/components/BottomNavigationBar/style.ts
  client/src/components/MainContainer/index.tsx
  client/src/components/MainContainer/style.ts
  client/src/constants/enums.ts
  client/src/pages/HomePage/index.tsx
  client/src/pages/HomePage/style.ts
  client/src/pages/PageTemplate.tsx
Labels: 🎨 style, ✨ feature, 🛶 frontend

#90 [BE] API 구현 - Record API - Best & Every SBD Record API 구현
  server/src/sbd_records/dto/best-record.dto.ts
  server/src/sbd_records/dto/every-record.dto.ts
  server/src/sbd_records/sbd_records.controller.ts
  server/src/sbd_records/sbd_records.service.ts
Labels: ✨ feature, 🚀 backend

#100 [BE] API 구현 - Search API 구현 (공통) - Every User Name API 구현
  server/src/users/entities/user.entity.ts
  server/src/users/users.controller.ts
  server/src/users/users.service.ts
Labels: ✨ feature, 🚀 backend

#97 [BE] API 구현 - Alarm API 구현 (공통) - Fetch Unread Alram API 구현
  server/src/alarms/alarms.controller.ts
  server/src/alarms/alarms.service.ts
  server/src/alarms/entities/alram.entity.ts
  server/src/users/entities/user.entity.ts
Labels: ✨ feature, 🚀 backend

#99 [BE] API 구현 - USER API (공통) - Get User Data API 구현
  server/src/users/entities/user.entity.ts
  server/src/users/users.controller.ts
  server/src/users/users.service.ts
Labels: ✨ feature, 🚀 backend

#102 [BE] API 구현 - AUTH API - JWT 구현
  server/package-lock.json
  server/package.json
  server/src/main.ts
  server/src/oauth/google-oauth/dto/create-google-oauth.dto.ts
  server/src/oauth/google-oauth/dto/google-user.dto.ts
  server/src/oauth/google-oauth/dto/update-google-oauth.dto.ts
  server/src/oauth/google-oauth/google-oauth.controller.ts
  server/src/oauth/google-oauth/google-oauth.module.ts
  server/src/oauth/google-oauth/google-oauth.service.ts
  server/src/oauth/google-oauth/utils/google.guards.ts
  server/src/oauth/google-oauth/utils/google.serializer.ts
  server/src/oauth/google-oauth/utils/google.strategy.ts
  server/src/oauth/jwt/jwt.strategy.ts
  server/src/types/jwt.d.ts
  server/src/types/request.d.ts
  server/src/types/request.type.ts
  server/src/types/user.type.ts
  server/src/users/entities/user.entity.ts
Labels: ✨ feature, 🚀 backend

#88 [FE] 홈 페이지 - 메인 - 프로필 이미지 컨테이너 리팩토링
  client/src/components/ProfileImageContainer/index.tsx
  client/src/components/ProfileImageContainer/style.ts
  client/src/stories/BottomNavigationBar.stories.tsx
  client/src/stories/Calendar.stories.tsx
Labels: 🛶 frontend, ♻ refactor

#114 [FE] 코어 - 공통 레이아웃 - 모달 디자인
  client/.storybook/main.js
  client/package-lock.json
  client/package.json
  client/public/icons/btn_cancel.svg
  client/src/components/design/Button/index.tsx
  client/src/components/design/Modal/index.tsx
  client/src/components/design/Modal/style.ts
  client/src/stores/modalStore.ts
  client/src/stories/Modal.stories.tsx
  client/tsconfig.json
Labels: 🎨 style, ✨ feature, 🛶 frontend

#116 [BE] API 구현 - USER API - Register User Data API 구현
  server/src/oauth/google-oauth/google-oauth.service.ts
  server/src/users/dto/users-info.dto.ts
  server/src/users/entities/user.entity.ts
  server/src/users/users.controller.ts
  server/src/users/users.service.ts
Labels: ✨ feature, 🚀 backend

#118 [FE] 홈 페이지 - 메인 - 3대 챌린지 버튼 & 운동 기록 버튼 구현
  client/public/icons/btn_arrow_right.svg
  client/public/icons/mark_arrow_right.svg
  client/src/components/UserInfoSummary/index.tsx
  client/src/constants/enums.ts
  client/src/pages/HomePage/index.tsx
  client/src/pages/HomePage/style.ts
Labels: 🎨 style, ✨ feature, 🛶 frontend

#125 [BE] API 구현 - USER API - Get User Challenge Timestamp API 구현
  server/src/app.module.ts
  server/src/exception/http-error.ts
  server/src/exception/http-exception.filter.ts
  server/src/main.ts
  server/src/oauth/google-oauth/google-oauth.service.ts
  server/src/sbd_records/entities/sbd_record.entity.ts
  server/src/users/users.controller.ts
  server/src/users/users.module.ts
  server/src/users/users.service.ts
Labels: ✨ feature, 🚀 backend

#121 [FE] 코어 - 공통 레이아웃 - 검색결과 프로필 / 프로필 사진 깨지는 현상 해결
  client/src/components/ProfileImageContainer/index.tsx
  client/src/components/ProfileImageContainer/style.ts
  client/src/components/SearchResultProfile/index.tsx
  client/src/components/SearchResultProfile/style.ts
  client/src/components/SearchResultUserProfile/index.tsx
  client/src/components/SearchResultUserProfile/style.ts
  client/src/stories/SearchResultProfile.stories.tsx
Labels: 🎨 style, ✨ feature, 🛶 frontend, ♻ refactor

#127 [FE] 코어 - 공통 레이아웃 - 달력 (타입 설정 및 스타일 변경)
  client/src/components/Calendar/CalendarBody.tsx
  client/src/components/Calendar/CalendarElement.tsx
  client/src/components/Calendar/CalendarHeader.tsx
  client/src/components/Calendar/style.ts
  client/src/pages/HomePage/index.tsx
Labels: 🎨 style, 🛶 frontend, ♻ refactor

#136 [FE] 코어 - 공통 레이아웃 - 달력 (색상 재지정)
  client/src/components/Calendar/CalendarElement.tsx
  client/src/constants/enums.ts
Labels: 🕷 bug, 🎨 style, 🛶 frontend

#137 [BE] ERD 최종본 바탕으로 Entity 수정
  server/src/alarms/alarms.service.ts
  server/src/alarms/entities/alram.entity.ts
  server/src/config/typeorm.config.ts
  server/src/exercises/entities/exercise.entity.ts
  server/src/routines/entities/routine.entity.ts
  server/src/sbd_records/entities/sbd_record.entity.ts
  server/src/users/entities/user.entity.ts
  server/src/users/users.controller.ts
Labels: 🚀 backend, ♻ refactor

#138 [BE] API 구현 - Exercise API - getTotalVolume 구하는 로직 수정
  server/src/exercises/exercises.service.ts
Labels: 🕷 bug, 🚀 backend

#142 [BE] API 구현 - USER API - DTO 추가 & 리펙토링
  server/package-lock.json
  server/package.json
  server/src/main.ts
  server/src/sbd_records/sbd_records.controller.ts
  server/src/sbd_records/sbd_records.service.ts
  server/src/users/dto/users-info.dto.ts
Labels: ✨ feature, 🚀 backend

#144 [BE] API 구현 - OAuth API - DTO 설정 추가
  server/src/oauth/google-oauth/dto/google-user.dto.ts
  server/src/oauth/google-oauth/google-oauth.controller.ts
  server/src/users/users.service.ts
Labels: ✨ feature, 🚀 backend, ♻ refactor

#147 [BE] API 구현 - 세팅 - API 요청 데이터 검증 절차 구현 (1차)
  server/src/alarms/alarms.controller.ts
  server/src/exception/exceptions.ts
  server/src/exercises/exercises.controller.ts
  server/src/exercises/exercises.service.ts
  server/src/routines/routines.controller.ts
  server/src/sbd_records/sbd_records.controller.ts
  server/src/users/users.controller.ts
  server/src/validation/validation.ts
Labels: 🚀 backend, ♻ refactor

#146 [BE] API 구현 - Dto에서의 converter 로직 분리
  server/src/exercises/converter/exercise.converter.ts
  server/src/exercises/dto/every-date.dto.ts
  server/src/exercises/dto/history-of-month.dto.ts
  server/src/exercises/exercises.service.ts
  server/src/routines/converter/routines.converter.ts
  server/src/routines/dto/routine-list.dto.ts
  server/src/routines/routines.service.ts
Labels: 🚀 backend, ♻ refactor

#151 [BE] API 구현 - Dto에서의 converter 로직 분리 완료
  server/src/config/typeorm.config.ts
  server/src/exercises/converter/exercise.converter.ts
  server/src/sbd_records/converter/sbd_records.converter.ts
  server/src/sbd_records/dto/best-record.dto.ts
  server/src/sbd_records/dto/every-record.dto.ts
  server/src/sbd_records/sbd_records.service.ts
Labels: 🚀 backend, ♻ refactor

#156 [BE] API 구현 - API 응답 단일화
  server/src/converter/response.converter.ts
  server/src/domain/alarms/alarms.controller.ts
  server/src/domain/alarms/alarms.service.ts
  server/src/domain/exercises/exercises.service.ts
  server/src/domain/follows/follows.controller.ts
  server/src/domain/follows/follows.service.ts
  server/src/domain/routines/dto/single-routine.dto.ts
  server/src/domain/routines/routines.controller.ts
  server/src/domain/routines/routines.service.ts
  server/src/domain/sbd_records/dto/single_sbd_data.dto.ts
  server/src/domain/sbd_records/sbd_records.controller.ts
  server/src/domain/sbd_records/sbd_records.service.ts
  server/src/domain/sbd_statistics/sbd_statistics.controller.ts
  server/src/domain/sbd_statistics/sbd_statistics.service.ts
  server/src/domain/users/users.controller.ts
  server/src/domain/users/users.service.ts
  server/src/exception/exceptions.ts
  server/tsconfig.json
Labels: 🚀 backend, ♻ refactor

#167 [BE] API 구현 - Get Every Exercise Date API 날짜 중복 제거
  server/src/domain/exercises/converter/exercise.converter.ts
  server/src/main.ts
Labels: 🕷 bug, 🚀 backend

#168 ♻️ [refactor] : Controller 내 불필요한 async 키워드 제거
  server/src/domain/routines/routines.controller.ts
  server/src/domain/users/users.controller.ts
  server/src/domain/users/users.service.ts
Labels: 🚀 backend, ♻ refactor

#166 [FE] 검색 페이지 - 메인 - 검색기능 및 사용자 추천 자동완성 기능
  client/src/App.tsx
  client/src/components/SearchResultUserProfile/index.tsx
  client/src/components/SearchResultUserProfile/style.ts
  client/src/pages/SearchPage/index.tsx
  client/src/pages/SearchPage/styles.ts
Labels: 🎨 style, ✨ feature, 🛶 frontend

#162 [BE] API 구현 - Get User Name List API - 프로필 요약 정보를 응답하도록 수정
  server/src/config/typeorm.config.ts
  server/src/domain/users/users.controller.ts
  server/src/domain/users/users.service.ts
Labels: ✨ feature, 🚀 backend

#173 서버 배포 1차 - storybook 삭제
  client/package.json
  client/src/stories/BottomNavigationBar.stories.tsx
  client/src/stories/Button.stories.tsx
  client/src/stories/Calendar.stories.tsx
  client/src/stories/CalendarHeatMap.stories.tsx
  client/src/stories/CardsScroller.stories.tsx
  client/src/stories/Modal.stories.tsx
  client/src/stories/Paper.stories.tsx
  client/src/stories/ProfileImageContainer.stories.tsx
  client/src/stories/SearchResultProfile.stories.tsx
  client/src/stories/TopNavigationBar.stories.tsx
Labels: 🕷 bug, ✨ feature, 🚀 backend

#176 서버 배포 1차 - axios 설치 & app.config.json
  client/app.config.json
  client/package-lock.json
  client/package.json
Labels: ⚙ setting, 🛶 frontend

#177 서버 배포 1차 - app.config.json
  client/app.config.json
Labels: 🕷 bug, ⚙ setting, 🛶 frontend

#183 [FE] 프로필 페이지 - 로그인 - Google OAuth
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/BottomNavigationButton/index.tsx
  client/src/components/GoogleOAuthButton/index.tsx
  client/src/components/GoogleOAuthButton/style.ts
  client/src/components/MainContainer/style.ts
  client/src/components/SearchResultUserProfile/index.tsx
  client/src/components/SearchResultUserProfile/style.ts
  client/src/components/design/Paper/style.ts
  client/src/constants/enums.ts
  client/src/pages/LoginPage/index.tsx
  client/src/pages/LoginPage/style.ts
  client/src/pages/ProfilePage/index.tsx
  client/src/pages/ProfilePage/style.ts
  client/src/pages/SearchPage/index.tsx
  client/src/pages/SearchPage/styles.ts
  client/src/services/HttpClient.ts
  client/src/types/http.d.ts
  client/src/types/png.d.ts
  server/src/config/typeorm.config.ts
  server/src/domain/users/users.controller.ts
  server/src/domain/users/users.service.ts
Labels: 🎨 style, ✨ feature, 🛶 frontend, ♻ refactor

#184 서버 배포 1차 - 검색 페이지 수정, 로그인 페이지 추가
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/BottomNavigationButton/index.tsx
  client/src/components/GoogleOAuthButton/index.tsx
  client/src/components/GoogleOAuthButton/style.ts
  client/src/components/MainContainer/style.ts
  client/src/components/SearchResultUserProfile/index.tsx
  client/src/components/SearchResultUserProfile/style.ts
  client/src/components/design/Paper/style.ts
  client/src/constants/enums.ts
  client/src/pages/LoginPage/index.tsx
  client/src/pages/LoginPage/style.ts
  client/src/pages/ProfilePage/index.tsx
  client/src/pages/ProfilePage/style.ts
  client/src/pages/SearchPage/index.tsx
  client/src/pages/SearchPage/styles.ts
  client/src/services/HttpClient.ts
  client/src/types/http.d.ts
  client/src/types/png.d.ts
  server/src/config/typeorm.config.ts
  server/src/domain/mock/fillna.py
  server/src/domain/users/users.controller.ts
  server/src/domain/users/users.service.ts
Labels: 🛶 frontend, ♻ refactor

#186 서버 배포 1차 - storybook 삭제
  client/package.json
Labels: 🕷 bug, 🛶 frontend

#188 서버 배포 1차 - cors 에러 수정
  client/src/pages/SearchPage/index.tsx
  server/src/main.ts
Labels: 🕷 bug, 🚀 backend, 🛶 frontend

#191 서버 배포 1차 - cors 수정
  server/src/main.ts
Labels: 🕷 bug, 🚀 backend

#193 서버 배포 1차 - cors 수정
  client/src/pages/SearchPage/index.tsx
  server/src/main.ts
Labels: 🚀 backend, 🛶 frontend

#196 서버 배포 1차 - CORS 오류 해결
  client/src/pages/SearchPage/index.tsx
  server/src/main.ts
Labels: 🕷 bug, ✨ feature, 🚀 backend

#197 [FE] 프로필 페이지 - 회원가입 - UI 구현
  client/package-lock.json
  client/package.json
  client/public/images/femaleSymbol.png
  client/public/images/maleSymbol.png
  client/src/App.tsx
  client/src/components/AgeGenderInputSet/index.tsx
  client/src/components/AgeGenderInputSet/style.ts
  client/src/components/BackButton/index.tsx
  client/src/components/BodyInfoInputSet/index.tsx
  client/src/components/BodyInfoInputSet/style.ts
  client/src/components/GoogleOAuthButton/index.tsx
  client/src/components/MainContainer/index.tsx
  client/src/components/MainContainer/style.ts
  client/src/components/NicknameTextField/index.tsx
  client/src/components/NicknameTextField/style.ts
  client/src/components/TopNavigationBar/index.tsx
  client/src/components/TopNavigationBar/style.ts
  client/src/components/UserInfoSummary/style.ts
  client/src/constants/consts.ts
  client/src/constants/enums.ts
  client/src/hooks/useInputFocus.ts
  client/src/pages/HomePage/style.ts
  client/src/pages/JoinPage/index.tsx
  client/src/pages/JoinPage/style.ts
  client/src/pages/LoginPage/index.tsx
  client/src/pages/LoginPage/style.ts
  client/src/pages/PageTemplate.tsx
  client/src/styles/TextField.ts
  client/src/styles/Theme.ts
  client/src/types/user.d.ts
  client/src/utils/UserValidation.ts
Labels: 🎨 style, ✨ feature, 🛶 frontend, ♻ refactor

#204 [FE] 검색페이지 - 메인 - 리팩토링 및 스타일링
  client/package-lock.json
  client/src/pages/SearchPage/index.tsx
  client/src/pages/SearchPage/styles.ts
  client/src/types/user.d.ts
Labels: 🎨 style, 🛶 frontend, ♻ refactor

#201 [FE] 코어 - 스타일 - 디자인 피드백 적용
  client/public/fonts/Pretendard-Regular.woff2
  client/public/fonts/Pretendard-SemiBold.woff2
  client/public/icons/btn_statics.svg
  client/src/components/BottomNavigationBar/style.ts
  client/src/components/BottomNavigationButton/style.ts
  client/src/components/Calendar/style.ts
  client/src/components/CalendarHeatMap/style.ts
  client/src/components/MainContainer/index.tsx
  client/src/components/MainContainer/style.ts
  client/src/components/UserInfoSummary/style.ts
  client/src/pages/HomePage/style.ts
  client/src/pages/JoinPage/index.tsx
  client/src/pages/PageTemplate.tsx
  client/src/styles/GlobalStyle.ts
  client/src/types/woff2.d.ts
Labels: 🎨 style, 🛶 frontend, ♻ refactor

#207 [FE] 홈 페이지 - 챌린지 - UI 구현
  client/public/images/img_benchpress.jpg
  client/public/images/img_deadlift.jpg
  client/public/images/img_female_symbol.png
  client/public/images/img_male_symbol.png
  client/public/images/img_squat.jpg
  client/src/App.tsx
  client/src/components/AgeGenderInputSet/index.tsx
  client/src/components/AgeGenderInputSet/style.ts
  client/src/components/BodyInfoInputSet/style.ts
  client/src/components/Calendar/style.ts
  client/src/components/ChallengeItem/index.tsx
  client/src/components/ChallengeItem/style.ts
  client/src/components/NicknameTextField/style.ts
  client/src/components/TopNavigationBar/style.ts
  client/src/components/design/Button/index.tsx
  client/src/components/design/Button/style.ts
  client/src/constants/enums.ts
  client/src/hooks/useTimeCount.ts
  client/src/pages/ChallengePage/index.tsx
  client/src/pages/ChallengePage/style.ts
  client/src/pages/HomePage/style.ts
  client/src/pages/JoinPage/style.ts
  client/src/stories/Button.stories.tsx
  client/src/styles/TextField.ts
  client/src/styles/components.ts
  client/src/types/asset.d.ts
  client/src/types/jpeg.d.ts
  client/src/types/png.d.ts
  client/src/types/svg.d.ts
  client/src/types/woff2.d.ts
  client/src/utils/addZeroPaddingToNumber.ts
  client/src/utils/calculateRemainingTime.ts
Labels: 🎨 style, ✨ feature, 🛶 frontend, ♻ refactor

#223 📝 [docs] : README 수정
  README.md
  fitory-logo.png
Labels: 📃 documentation

#208 [FE] 검색 페이지 - 검색페이지 - UI 구현
  client/src/pages/SearchPage/index.tsx
  client/src/pages/SearchPage/styles.ts
Labels: 🎨 style, ✨ feature, 🛶 frontend

#212 [BE] API 구현 - AUTH API - Google OAuth 프론트와의 연동성 수정
  server/package-lock.json
  server/package.json
  server/src/domain/oauth/google-oauth/dto/access-token.dto.ts
  server/src/domain/oauth/google-oauth/google-oauth.controller.ts
  server/src/domain/oauth/google-oauth/google-oauth.module.ts
  server/src/domain/oauth/google-oauth/google-oauth.service.ts
  server/src/domain/oauth/google-oauth/utils/google.strategy.ts
Labels: 🕷 bug, 🚀 backend

#214 [BE] API 구현 - USER API - user name 중복 검사
  server/src/domain/users/users.controller.ts
  server/src/domain/users/users.service.ts
  server/src/exception/exceptions.ts
Labels: ✨ feature, 🚀 backend

#216 [BE] API 구현 - RECOMMAND API - 유저 친구 추천
  server/src/domain/users/users.controller.ts
  server/src/domain/users/users.service.ts
Labels: ✨ feature, 🚀 backend

#224 [FE] 홈 페이지 - 운동 기록 - UI 구현
  client/package-lock.json
  client/package.json
  client/public/icons/btn_exercise_complete.svg
  client/public/icons/btn_exercise_fail.svg
  client/src/App.tsx
  client/src/components/ExerciseInputSet/index.tsx
  client/src/components/ExerciseInputSet/style.ts
  client/src/components/RoutineScroller/index.tsx
  client/src/components/RoutineScroller/style.ts
  client/src/components/design/Paper/index.tsx
  client/src/components/design/Paper/style.ts
  client/src/pages/RecordPage/index.tsx
  client/src/pages/RecordPage/style.ts
Labels: 🎨 style, ✨ feature, 🛶 frontend

#218 [BE] API 구현 - Alarm - Get Alarm List
  server/src/domain/alarms/alarms.controller.ts
  server/src/domain/alarms/alarms.module.ts
  server/src/domain/alarms/alarms.service.ts
Labels: ✨ feature, 🚀 backend

#222 [BE] API 구현 - Record - Submit Record API 구현
  server/src/domain/sbd_records/dto/single_sbd_data.dto.ts
  server/src/domain/sbd_records/sbd_records.controller.ts
  server/src/domain/sbd_records/sbd_records.module.ts
  server/src/domain/sbd_records/sbd_records.service.ts
  server/src/exception/exceptions.ts
Labels: ✨ feature, 🚀 backend

#227 [BE] API 구현 - Follow - Get Following / Follower List API 구현
  server/src/domain/follows/follows.controller.ts
  server/src/domain/follows/follows.module.ts
  server/src/domain/follows/follows.service.ts
Labels: ✨ feature, 🚀 backend

#231 [FE] 통계 페이지 - 티어 변동 - 티어 그래프
  client/package-lock.json
  client/package.json
  client/src/components/TierGraph/index.tsx
  client/src/components/TierGraph/mockData.ts
  client/src/components/TierGraph/option.ts
  client/src/components/TierGraph/plugin.ts
  client/src/components/TierGraph/utils.ts
  client/src/stories/TierChart.stories.tsx
  client/src/types/user.d.ts
Labels: 🎨 style, ✨ feature, 🛶 frontend

#229 [BE] API 구현 - ROUTINE API - Get Single Routine API 구현
  server/src/domain/routines/routines.controller.ts
  server/src/domain/routines/routines.service.ts
  server/src/exception/exceptions.ts
Labels: ✨ feature, 🚀 backend

#234 [BE] dev 브랜치 발생 에러 해결
  server/src/domain/users/users.service.ts
  server/src/exception/exceptions.ts
Labels: 🕷 bug, 🚀 backend

#242 [BE] API 구현 - OAUTH API - 구글 로그인 프론트 연동 수정
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/domain/oauth/google-oauth/dto/access-token.dto.ts
  server/src/domain/oauth/google-oauth/google-oauth.controller.ts
  server/src/domain/oauth/google-oauth/google-oauth.module.ts
  server/src/domain/oauth/google-oauth/google-oauth.service.ts
  server/src/domain/oauth/google-oauth/utils/google.strategy.ts
  server/src/main.ts
Labels: 🕷 bug, ✨ feature, 🚀 backend

#249 [BE] API 구현 - AUTH API - 로그인, 회원가입 구분, 쿠키 수정, DB에 유저 정보 저장
  server/src/domain/oauth/google-oauth/dto/google-user-info.dto.ts
  server/src/domain/oauth/google-oauth/dto/google-user-register.dto.ts
  server/src/domain/oauth/google-oauth/dto/google-user.dto.ts
  server/src/domain/oauth/google-oauth/google-oauth.controller.ts
  server/src/domain/oauth/google-oauth/google-oauth.service.ts
  server/src/domain/users/entities/user.entity.ts
  server/src/domain/users/users.controller.ts
  server/src/domain/users/users.service.ts
  server/src/types/request.d.ts
Labels: ✨ feature, 🚀 backend
