Repository boostcampwm-2022/Web04-Fitory, pull requests merged in 2022-12, with the labels that each got.

#261 [BE] API 구현 - AUTH API - 쿠키 기한 수정, 리팩토링
  server/src/domain/oauth/google-oauth/google-oauth.controller.ts
  server/src/domain/oauth/google-oauth/google-oauth.module.ts
  server/src/domain/users/users.controller.ts
Labels: 🚀 backend, ♻ refactor

#250 [BE] DB - 데이터 - multer 모듈로 이미지 저장 구현
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/domain/uploads/multer_options.ts
  server/src/domain/uploads/upload.controller.ts
  server/src/domain/uploads/upload.module.ts
  server/src/domain/uploads/upload.service.ts
  server/src/exception/exceptions.ts
  server/src/main.ts
Labels: ✨ feature, 🚀 backend

#252 [FE] 통계 페이지 - 메인 - 레이아웃 및 구현작업
  client/src/App.tsx
  client/src/components/Carousel/index.tsx
  client/src/components/Carousel/style.ts
  client/src/components/ExerciseScoreContainer/index.tsx
  client/src/components/ExerciseScoreContainer/style.ts
  client/src/components/StaticsUserInfoContainer/index.tsx
  client/src/components/StaticsUserInfoContainer/style.ts
  client/src/components/TierGraph/index.tsx
  client/src/components/TierGraph/plugin.ts
  client/src/pages/SearchPage/index.tsx
  client/src/pages/StaticsPage/index.tsx
  client/src/pages/StaticsPage/style.ts
Labels: 🎨 style, ✨ feature, 🛶 frontend

#256 [FE] 홈 페이지 - 운동 기록 - 상태 관리
  client/src/components/ExerciseInputSet/index.tsx
  client/src/components/ExerciseRecordItem/ExerciseSetItem.tsx
  client/src/components/ExerciseRecordItem/index.tsx
  client/src/components/ExerciseRecordItem/style.ts
  client/src/pages/RecordPage/index.tsx
  client/src/stores/exerciseStore.ts
  client/src/types/exercise.d.ts
  client/src/utils/updateOneElementFromArray.ts
Labels: ✨ feature, 🛶 frontend, ♻ refactor

#263 [FE] 로그인 / 회원가입 페이지 - API 연동
  client/package-lock.json
  client/package.json
  client/public/images/btn_google_signin.png
  client/src/App.tsx
  client/src/api/UserAPI.ts
  client/src/components/AgeGenderInputSet/index.tsx
  client/src/components/BodyInfoInputSet/index.tsx
  client/src/components/GoogleOAuthButton/index.tsx
  client/src/components/GoogleOAuthButton/style.ts
  client/src/components/NicknameTextField/index.tsx
  client/src/hooks/query/useGoogleLogin.ts
  client/src/hooks/query/useJoinUser.ts
  client/src/pages/JoinPage/index.tsx
  client/src/pages/ProfilePage/index.tsx
  client/src/services/ClientStorage.ts
  client/src/services/HttpClient.ts
  client/src/types/user.d.ts
Labels: ✨ feature, 🛶 frontend

#276 [BE] DB - Soft Delete 적용
  server/package-lock.json
  server/package.json
  server/src/domain/follows/entities/follow.entity.ts
  server/src/domain/follows/follows.service.ts
  server/src/domain/routines/entities/routine.entity.ts
  server/src/domain/routines/routines.service.ts
  server/src/main.ts
Labels: ✨ feature, 🚀 backend

#262 [BE] API 구현 - AUTH API - Get 'userId' from Access Token Guard & Decorator 구현
  server/src/app.module.ts
  server/src/decorator/validate.decorator.ts
  server/src/domain/oauth/google-oauth/google-oauth.module.ts
  server/src/domain/oauth/jwt/jwt.guard.ts
  server/src/domain/oauth/jwt/jwt.strategy.ts
  server/src/exception/exceptions.ts
  server/src/types/jwt.d.ts
Labels: ✨ feature, 🚀 backend

#275 [BE] API - DTO 검증 수정
  server/src/domain/exercises/dto/exercise.dto.ts
  server/src/domain/oauth/google-oauth/dto/google-user-info.dto.ts
  server/src/domain/oauth/google-oauth/dto/google-user-register.dto.ts
  server/src/domain/routines/dto/single-routine.dto.ts
  server/src/domain/sbd_records/dto/single_sbd_data.dto.ts
  server/src/domain/sbd_records/sbd_records.controller.ts
  server/src/domain/sbd_records/sbd_records.service.ts
  server/src/domain/users/dto/users-info.dto.ts
  server/src/domain/users/users.controller.ts
  server/src/domain/users/users.service.ts
Labels: 🚀 backend, ♻ refactor

#279 [BE] API - Follow - Do & Cancel Follow API 구현
  server/src/domain/exercises/dto/exercise.dto.ts
  server/src/domain/follows/dto/follow.dto.ts
  server/src/domain/follows/follows.controller.ts
  server/src/domain/follows/follows.service.ts
  server/src/exception/exceptions.ts
Labels: ✨ feature, 🚀 backend

#281 [FE] 홈 페이지 - API 연동
  client/src/api/ChallengeAPI.ts
  client/src/api/ExerciseAPI.ts
  client/src/api/UserAPI.ts
  client/src/components/Calendar/CalendarBody.tsx
  client/src/components/CalendarHeatMap/index.tsx
  client/src/components/UserInfoSummary/index.tsx
  client/src/components/UserInfoSummary/style.ts
  client/src/constants/enums.ts
  client/src/hooks/query/useAllExerciseDate.ts
  client/src/hooks/query/useBestChallengeScore.ts
  client/src/hooks/query/useExerciseProfile.ts
  client/src/hooks/query/useUserInfo.ts
  client/src/services/Exception.ts
  client/src/services/HttpClient.ts
  client/src/types/challenge.d.ts
  client/src/types/exercise.d.ts
  client/src/utils/convertWeightUnits.ts
Labels: ✨ feature, 🛶 frontend, ♻ refactor

#283 [BE] API - Exercise - 운동 완료시 알람 발송 기능 구현
  server/src/config/typeorm.config.ts
  server/src/domain/alarms/alarms.module.ts
  server/src/domain/alarms/alarms.service.ts
  server/src/domain/exercises/exercises.controller.ts
  server/src/domain/exercises/exercises.module.ts
  server/src/domain/users/users.service.ts
Labels: ✨ feature, 🚀 backend

#294 [BE] 코어 - 서버 환경 설정 - .env 설정 수정
  client/src/pages/SearchPage/index.tsx
  client/src/stories/BottomNavigationBar.stories.tsx
  client/src/stories/Calendar.stories.tsx
  client/src/stories/CalendarHeatMap.stories.tsx
  client/src/stories/CardsScroller.stories.tsx
  client/src/stories/Modal.stories.tsx
  client/src/stories/Paper.stories.tsx
  client/src/stories/ProfileImageContainer.stories.tsx
  client/src/stories/SearchResultProfile.stories.tsx
  client/src/stories/TopNavigationBar.stories.tsx
  server/src/main.ts
  server/src/utils/env.ts
Labels: 🚀 backend, ♻ refactor, 🚨 deploy

#295 [FE] 회원가입 닉네임 중복 여부 확인 API 버그 & React Query 비동기 처리 에러 해결
  client/src/App.tsx
  client/src/api/ChallengeAPI.ts
  client/src/api/ExerciseAPI.ts
  client/src/api/UserAPI.ts
  client/src/pages/JoinPage/index.tsx
  client/src/services/ClientStorage.ts
  client/src/types/challenge.d.ts
  client/src/types/user.d.ts
Labels: 🐛 bug, 🛶 frontend

#300 서버 배포 2차 - 파일 이름 오류 수정
  client/src/styles/Components.ts
Labels: 🐛 bug, 🚨 deploy

#302 서버 배포 2차 - cookie secure 설정 변경
  server/src/domain/oauth/google-oauth/google-oauth.controller.ts
Labels: 🚨 deploy

#289 [FE] 마이페이지 - 팔로우/팔로잉 - 리스트받아오기, 검색
  client/package-lock.json
  client/src/App.tsx
  client/src/constants/enums.ts
  client/src/pages/FollowPage/index.tsx
  client/src/pages/FollowPage/style.ts
  client/src/pages/ProfilePage/index.tsx
  client/src/pages/SearchPage/index.tsx
  client/src/pages/SearchPage/styles.ts
  client/src/pages/SearchPage/utils.tsx
  client/src/types/user.d.ts
  client/src/utils/SearchUtils.ts
  client/src/utils/drawSearchedUserList.tsx
Labels: ✨ feature, 🛶 frontend, ♻ refactor

#303 서버 배포 2차 - #289 PR 적용
  client/package-lock.json
  client/src/App.tsx
  client/src/constants/enums.ts
  client/src/pages/FollowPage/index.tsx
  client/src/pages/FollowPage/style.ts
  client/src/pages/ProfilePage/index.tsx
  client/src/pages/SearchPage/index.tsx
  client/src/pages/SearchPage/styles.ts
  client/src/pages/SearchPage/utils.tsx
  client/src/types/user.d.ts
  client/src/utils/SearchUtils.ts
  client/src/utils/drawSearchedUserList.tsx
Labels: 🐛 bug, 🚨 deploy

#306 서버 배포 2차 - 사용자 검증 오류 수정
  client/src/services/HttpClient.ts
  server/src/domain/alarms/alarms.controller.ts
  server/src/domain/users/users.service.ts
  server/src/validation/validation.ts
Labels: 🐛 bug, 🚨 deploy

#307 storybook rollback
  client/src/pages/SearchPage/index.tsx
  client/src/stories/BottomNavigationBar.stories.tsx
  client/src/stories/Calendar.stories.tsx
  client/src/stories/CalendarHeatMap.stories.tsx
  client/src/stories/CardsScroller.stories.tsx
  client/src/stories/Modal.stories.tsx
  client/src/stories/Paper.stories.tsx
  client/src/stories/ProfileImageContainer.stories.tsx
  client/src/stories/SearchResultProfile.stories.tsx
  client/src/stories/TopNavigationBar.stories.tsx
  server/src/main.ts
  server/src/utils/env.ts
Labels: 🐛 bug, 🛶 frontend

#288 [BE] API 구현 - ROUTINE API - Save Routine API
  server/src/domain/exercises/dto/exercise.dto.ts
  server/src/domain/exercises/exercises.service.ts
  server/src/domain/routines/converter/routines.converter.ts
  server/src/domain/routines/dto/single-routine.dto.ts
  server/src/domain/routines/routines.controller.ts
  server/src/domain/routines/routines.service.ts
  server/src/exception/exceptions.ts
  server/src/types/domain.d.ts
Labels: ✨ feature, 🚀 backend

#287 [BE] API - 팔로우 요청시 팔로잉 당하는 사용자에게 알람 발송 기능 구현
  server/src/domain/alarms/alarms.service.ts
  server/src/domain/follows/follows.controller.ts
  server/src/domain/follows/follows.module.ts
Labels: ✨ feature, 🚀 backend

#308 [BE] date를 서버 시간으로 조정
  server/src/domain/exercises/dto/exercise.dto.ts
  server/src/domain/exercises/exercises.service.ts
  server/src/domain/mock/mock.service.ts
  server/src/domain/sbd_records/converter/sbd_records.converter.ts
  server/src/domain/sbd_records/entities/sbd_record.entity.ts
  server/src/domain/sbd_records/sbd_records.service.ts
  server/src/domain/users/entities/user.entity.ts
  server/src/types/domain.d.ts
Labels: 🚀 backend, ♻ refactor

#290 [BE] API - Alarm 읽음 처리 구현
  server/src/domain/alarms/alarms.service.ts
  server/src/domain/follows/follows.service.ts
Labels: ✨ feature, 🚀 backend

#314 [BE} API - 대응 - 존재하지 않는 사용자 ID 요청 검증 취소
  server/src/domain/alarms/alarms.controller.ts
  server/src/domain/exercises/dto/exercise.dto.ts
  server/src/domain/exercises/exercises.controller.ts
  server/src/domain/follows/follows.controller.ts
  server/src/domain/routines/routines.controller.ts
  server/src/domain/sbd_records/sbd_records.controller.ts
  server/src/domain/users/users.controller.ts
Labels: 🚀 backend, ♻ refactor

#309 [FE] 챌린지 페이지 - API 연동
  client/package.json
  client/src/api/ChallengeAPI.ts
  client/src/constants/enums.ts
  client/src/hooks/query/useAllExerciseDate.ts
  client/src/hooks/query/useBestChallengeScore.ts
  client/src/hooks/query/useExerciseProfile.ts
  client/src/hooks/query/useRecentChallengeTime.ts
  client/src/hooks/query/useSubmitChallenge.ts
  client/src/hooks/query/useUserInfo.ts
  client/src/hooks/useDecreaseTime.ts
  client/src/hooks/useTimeCount.ts
  client/src/pages/ChallengePage/index.tsx
  client/src/styles/Components.ts
  client/src/types/challenge.d.ts
  client/src/utils/calculateRemainingTime.ts
  server/src/domain/alarms/alarms.controller.ts
  server/src/domain/oauth/google-oauth/google-oauth.controller.ts
  server/src/domain/sbd_records/dto/single_sbd_data.dto.ts
  server/src/domain/users/users.service.ts
  server/src/validation/validation.ts
Labels: ✨ feature, 🚀 backend, 🛶 frontend, ♻ refactor

#292 [BE] API 구현 - AUTH API - 유저 검증 middleware 구현
  client/src/pages/SearchPage/index.tsx
  server/src/app.module.ts
  server/src/config/typeorm.config.ts
  server/src/decorator/validate.decorator.ts
  server/src/domain/oauth/jwt/jwt.strategy.ts
  server/src/exception/exceptions.ts
  server/src/main.ts
  server/src/middleware/valid-user/valid-user.middleware.ts
  server/src/utils/env.ts
Labels: ✨ feature, 🚀 backend

#317 [FE] 운동 기록 페이지 - API 연동
  client/public/images/btn_routine_1.png
  client/public/images/btn_routine_2.png
  client/public/images/btn_routine_3.png
  client/public/images/btn_routine_4.png
  client/public/images/btn_routine_5.png
  client/public/images/btn_routine_6.png
  client/src/api/ExerciseAPI.ts
  client/src/api/UserAPI.ts
  client/src/components/ExerciseRecordItem/ExerciseSetItem.tsx
  client/src/components/ExerciseRecordItem/index.tsx
  client/src/components/ExerciseRecordList/index.tsx
  client/src/components/ExerciseRecordList/style.ts
  client/src/components/RoutineSaveButton/index.tsx
  client/src/components/RoutineSaveButton/style.ts
  client/src/components/RoutineScroller/index.tsx
  client/src/components/RoutineScroller/style.ts
  client/src/components/UserInfoSummary/index.tsx
  client/src/components/design/Modal/index.tsx
  client/src/components/design/Modal/style.ts
  client/src/constants/enums.ts
  client/src/hooks/query/useRecordExercise.ts
  client/src/hooks/query/useRoutineList.ts
  client/src/hooks/query/useSaveRoutine.ts
  client/src/hooks/query/useSubmitChallenge.ts
  client/src/hooks/query/useUserInfo.ts
  client/src/pages/RecordPage/index.tsx
  client/src/pages/RecordPage/style.ts
  client/src/services/ClientStorage.ts
  client/src/services/Exception.ts
  client/src/services/HttpClient.ts
  client/src/stores/exerciseStore.ts
  client/src/types/exercise.d.ts
  client/src/utils/getExerciseStateForOneYear.ts
Labels: 🎨 style, ✨ feature, 🛶 frontend, ♻ refactor

#327 [BE] API - Recommend - 응답 양식 수정
  server/src/domain/alarms/alarms.service.ts
  server/src/domain/users/users.controller.ts
  server/src/domain/users/users.service.ts
  server/src/middleware/valid-user/valid-user.middleware.ts
Labels: 🐛 bug, 🚀 backend, ♻ refactor

#315 [FE] 검색페이지 - 검색바 - 스타일링/ drawSearchedUserList 위치 변경
  client/src/components/SearchResultUserProfile/style.ts
  client/src/components/SearchedUserList/index.tsx
  client/src/components/SearchedUserList/style.ts
  client/src/pages/FollowPage/index.tsx
  client/src/pages/FollowPage/style.ts
  client/src/pages/SearchPage/index.tsx
  client/src/pages/SearchPage/styles.ts
  client/src/pages/SearchPage/utils.tsx
Labels: 🎨 style, 🛶 frontend, ♻ refactor

#318 [FE] 홈 페이지 - 잔디 - 개선하기
  client/src/components/CalendarHeatMap/index.tsx
  client/src/constants/enums.ts
  client/src/hooks/query/useAllExerciseDate.ts
  client/src/utils/getCalendarHeatMapArray.ts
  client/src/utils/getExerciseStateForOneYear.ts
Labels: 🐛 bug, 🛶 frontend, ♻ refactor

#326 [BE] API 구현 - Routine API
  server/src/domain/exercises/converter/exercise.converter.ts
  server/src/domain/routines/converter/routines.converter.ts
  server/src/domain/routines/dto/single-routine.dto.ts
  server/src/domain/routines/routines.controller.ts
  server/src/domain/routines/routines.service.ts
  server/src/domain/sbd_records/converter/sbd_records.converter.ts
  server/src/domain/users/users.service.ts
  server/src/exception/exceptions.ts
  server/src/types/domain.d.ts
Labels: 🐛 bug, ✨ feature, 🚀 backend

#331 [BE] API 구현 - AUTH API - middleware 예외처리 수정
  server/src/app.module.ts
  server/src/decorator/validate.decorator.ts
  server/src/domain/oauth/google-oauth/google-oauth.controller.ts
  server/src/domain/oauth/google-oauth/google-oauth.module.ts
  server/src/domain/oauth/google-oauth/google-oauth.service.ts
  server/src/domain/users/users.controller.ts
  server/src/exception/exceptions.ts
  server/src/guard/auth.guard.ts
  server/src/guard/jwt.guard.ts
  server/src/guard/jwt.strategy.ts
  server/src/main.ts
  server/src/middleware/valid-user/valid-user.middleware.ts
  server/tsconfig.json
Labels: 🐛 bug, ✨ feature, 🚀 backend

#330 [FE] 검색페이지 - 리팩토링 - api연동 / 디바운싱 적용
  client/src/api/UserAPI.ts
  client/src/components/MyPageUserProfile/index.tsx
  client/src/components/MyPageUserProfile/style.ts
  client/src/pages/ProfilePage/index.tsx
  client/src/pages/SearchPage/index.tsx
  client/src/pages/SearchPage/utils.tsx
  client/src/utils/SearchUtils.ts
Labels: ✨ feature, 🛶 frontend, ♻ refactor

#338 [BE] API 구현 - AUTH API - Guard 예외 처리
  server/src/domain/users/users.controller.ts
Labels: 🐛 bug, 🚀 backend

#347 [BE] API 구현 - AUTH API - guard 수정
  server/src/app.module.ts
  server/src/guard/auth.guard.ts
  server/src/guard/jwt.guard.ts
  server/src/main.ts
Labels: 🐛 bug, 🚀 backend

#325 [BE] API 구현 - Mypage - 마이페이지 수정 요청 API
  client/src/App.tsx
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/converter/response.converter.ts
  server/src/domain/alarms/alarms.controller.ts
  server/src/domain/uploads/multer_options.ts
  server/src/domain/uploads/upload.controller.ts
  server/src/domain/uploads/upload.module.ts
  server/src/domain/uploads/upload.service.ts
  server/src/domain/users/dto/user_profile.dto.ts
  server/src/domain/users/options/multer_options.ts
  server/src/domain/users/users.controller.ts
  server/src/domain/users/users.service.ts
Labels: ✨ feature, 🚀 backend

#350 [FE] 로그인 페이지 - UI 개선
  client/public/images/fitory-logo.png
  client/src/pages/LoginPage/index.tsx
  client/src/pages/LoginPage/style.ts
  client/src/services/HttpClient.ts
Labels: 🎨 style, 🛶 frontend

#345 [FE] 검색페이지 - 검색 / 추천친구 - 기능개선
  client/public/images/img_default_profile.png
  client/src/pages/SearchPage/index.tsx
  client/src/pages/SearchPage/styles.ts
  client/src/pages/SearchPage/utils.tsx
  client/src/utils/SearchUtils.ts
Labels: ✨ feature, 🛶 frontend, ♻ refactor

#357 [BE] API 구현 - AUTH API - AuthGuard 버그 수정
  server/src/app.module.ts
  server/src/exception/exceptions.ts
  server/src/guard/jwt.guard.ts
  server/src/guard/jwt.strategy.ts
  server/src/main.ts
Labels: 🐛 bug, 🚀 backend

#358 [FE] 코어 - 로그인 페이지 전환 예외 처리 구현
  client/package-lock.json
  client/src/api/ExerciseAPI.ts
  client/src/constants/enums.ts
  client/src/hooks/query/useUserInfo.ts
  client/src/pages/PageTemplate.tsx
  client/src/services/HttpClient.ts
Labels: ✨ feature, 🛶 frontend, ♻ refactor

#366 [FE] 회원가입 페이지 - 예외처리
  client/src/pages/JoinPage/index.tsx
  client/src/pages/PageTemplate.tsx
Labels: ✨ feature, 🛶 frontend, ✈️ Super Pass

#368 [BE] API 구현 - STATISTICS API
  server/src/domain/sbd_statistics/sbd_statistics.controller.ts
  server/src/domain/sbd_statistics/sbd_statistics.service.ts
  server/src/exception/exceptions.ts
Labels: ✨ feature, 🚀 backend

#361 [FE] Fitory 텍스트 로고 이미지 적용 (+ 잔디 에러 수정)
  client/public/icons/logo.svg
  client/public/images/fitory-logo.png
  client/public/images/img_logo_main.webp
  client/public/images/img_logo_text.webp
  client/src/components/TopNavigationBar/index.tsx
  client/src/components/TopNavigationBar/style.ts
  client/src/constants/enums.ts
  client/src/pages/LoginPage/index.tsx
  client/src/pages/LoginPage/style.ts
Labels: 🎨 style, 🛶 frontend, ♻ refactor

#371 [FE] 코어 - 불변성 관리
  client/package-lock.json
  client/package.json
  client/src/hooks/query/useBestChallengeScore.ts
  client/src/hooks/query/useExerciseProfile.ts
  client/src/hooks/query/useRecentChallengeTime.ts
  client/src/hooks/query/useRoutineList.ts
  client/src/hooks/query/useUserInfo.ts
  client/src/stores/exerciseStore.ts
  client/src/utils/updateOneElementFromArray.ts
Labels: 🛶 frontend, ♻ refactor

#378 [BE] API - Follow - FollowingCount, FollowerCount 컬럼 삭제
  server/package.json
  server/src/app.module.ts
  server/src/domain/follows/follows.service.ts
  server/src/domain/mock/mock.service.ts
  server/src/domain/users/dto/users-info.dto.ts
  server/src/domain/users/entities/user.entity.ts
  server/src/domain/users/users.controller.ts
  server/src/domain/users/users.module.ts
  server/src/domain/users/users.service.ts
Labels: 🐛 bug, 🚀 backend

#373 [FE] 마이페이지/ 팔로우페이지 - 레이아웃/팔로우 - 레이아웃작업 및 팔로우 팔로잉 기능 작업
  client/public/index.html
  client/src/App.tsx
  client/src/api/FollowAPI.ts
  client/src/api/UserAPI.ts
  client/src/components/FollowButton/index.tsx
  client/src/components/FollowButton/style.ts
  client/src/components/MyPageEditButton/index.tsx
  client/src/components/MyPageEditButton/style.ts
  client/src/components/MyPageSubInfoContainer/index.tsx
  client/src/components/MyPageSubInfoContainer/style.ts
  client/src/components/MyPageUserIntroduce/index.tsx
  client/src/components/MyPageUserIntroduce/style.ts
  client/src/components/MyPageUserProfile/index.tsx
  client/src/components/MyPageUserProfile/style.ts
  client/src/components/ProfileImageContainer/index.tsx
  client/src/components/SearchResultUserProfile/index.tsx
  client/src/components/SearchResultUserProfile/style.ts
  client/src/components/SearchedUserList/index.tsx
  client/src/pages/FollowPage/index.tsx
  client/src/pages/ProfilePage/index.tsx
  client/src/pages/ProfilePage/style.ts
  client/src/types/user.d.ts
  client/src/utils/getUserTierUtil.ts
Labels: 🎨 style, ✨ feature, 🛶 frontend, ♻ refactor

#385 서버 배포 3차 : 무중단 배포 설정
  server/src/middleware/zero-downtime-deploy/graceful-shutdown.ts
  server/src/middleware/zero-downtime-deploy/is-disable-keep-alive.global.ts
  server/src/middleware/zero-downtime-deploy/set-response-header.middleware.ts
Labels: 🚨 deploy, ✈️ Super Pass

#369 [BE] DB - mock 데이터 생성기 수정
  server/src/app.module.ts
  server/src/domain/mock/mock.controller.ts
  server/src/domain/mock/mock.service.ts
  server/src/domain/users/users.controller.ts
Labels: 🐛 bug, 🚀 backend

#377 [BE] SSE - EventEmitter로 알림 발생 이벤트 관리
  client/package.json
  client/public/index.html
  server/src/decorator/validate.decorator.ts
  server/src/domain/alarms/alarms.controller.ts
  server/src/domain/alarms/alarms.service.ts
  server/src/domain/follows/follows.service.ts
  server/src/domain/oauth/google-oauth/google-oauth.controller.ts
  server/src/guard/jwt.guard.ts
  server/src/guard/jwt.strategy.ts
  server/src/main.ts
  server/src/types/request.d.ts
Labels: ✨ feature, 🚀 backend

#387 [BE] API - Follow - 팔로우 취소 오류 수정
  server/package-lock.json
  server/package.json
  server/src/domain/follows/follows.service.ts
Labels: 🐛 bug, 🚀 backend

#389 [FE] 코어 - React Query 캐싱 문제 해결
  client/src/App.tsx
  client/src/api/ChallengeAPI.ts
  client/src/hooks/query/useAllExerciseDate.ts
  client/src/hooks/query/useBestChallengeScore.ts
  client/src/hooks/query/useExerciseProfile.ts
  client/src/hooks/query/useRecentChallengeTime.ts
  client/src/hooks/query/useRoutineList.ts
  client/src/hooks/query/useUserInfo.ts
Labels: 🛶 frontend, ♻ refactor

#391 [FE] 팔로우페이지 - 팔로우버튼 - 리팩토링
  client/.eslintrc.json
  client/src/components/FollowButton/index.tsx
  client/src/components/FollowButton/style.ts
  client/src/components/MyPageSubInfoContainer/index.tsx
  client/src/components/MyPageSubInfoContainer/style.ts
  client/src/components/MyPageUserIntroduce/index.tsx
  client/src/components/MyPageUserIntroduce/style.ts
  client/src/components/MyPageUserProfile/index.tsx
  client/src/components/MyPageUserProfile/style.ts
  client/src/components/SearchResultUserProfile/index.tsx
  client/src/pages/ProfilePage/index.tsx
Labels: 🛶 frontend, ♻ refactor

#392 [FE] 캘린더 - 개선
  client/src/api/ExerciseAPI.ts
  client/src/components/Calendar/CalendarBody.tsx
  client/src/components/Calendar/CalendarElement.tsx
  client/src/components/Calendar/CalendarHeader.tsx
  client/src/components/Calendar/index.tsx
  client/src/components/Calendar/style.ts
  client/src/components/ExerciseSetContainer/index.tsx
  client/src/components/ExerciseSetContainer/style.ts
  client/src/constants/enums.ts
  client/src/hooks/query/useRecordExercise.ts
  client/src/hooks/query/useSingleMonthExerciseHistory.ts
  client/src/pages/CalendarPage/index.tsx
  client/src/pages/CalendarPage/style.ts
  client/src/types/exercise.d.ts
Labels: 🎨 style, 🛶 frontend, ♻ refactor

#395 서버 배포 3차 - deploy 경로 수정
  .github/workflows/deplol.yml
  deploy.sh
Labels: 🚨 deploy, ✈️ Super Pass

#396 서버 배포 3차 : alarm sse CORS 수정
  server/src/domain/alarms/alarms.controller.ts
Labels: 🚨 deploy, ✈️ Super Pass

#398 서버 배포 3차 - index.html 삭제
  client/public/index.html
Labels: 🚨 deploy, ✈️ Super Pass

#399 서버 배포 3차 - allowedHeaders user_id 추가
  server/src/domain/mock/mock.service.ts
  server/src/guard/jwt.guard.ts
  server/src/main.ts
Labels: 🚨 deploy, ✈️ Super Pass

#401 서버 배포 3차 - allowedHeaders user_id 추가
  server/src/main.ts
Labels: 🚨 deploy, ✈️ Super Pass

#402 [FE] 마이 페이지 - 하단
  client/.eslintrc.json
  client/public/index.html
  client/src/components/MyPageEditButton/style.ts
  client/src/components/MyPageUserProfile/index.tsx
  client/src/components/MyPageUserProfile/style.ts
  client/src/pages/ProfilePage/index.tsx
  client/src/pages/ProfilePage/style.ts
  server/src/domain/mock/mock.controller.ts
Labels: 🎨 style, 🛶 frontend, ✈️ Super Pass

#403 [FE] 통계페이지 - 차트 - api 연동
  client/src/api/ExerciseAPI.ts
  client/src/components/TierGraph/index.tsx
  client/src/components/TierGraph/plugin.ts
  client/src/components/TierGraph/style.ts
  client/src/pages/ProfilePage/index.tsx
  client/src/types/exercise.d.ts
Labels: ✈️ Super Pass

#405 서버 배포 3차 - profile page import 추가
  client/src/pages/ProfilePage/index.tsx
Labels: 🚨 deploy, ✈️ Super Pass

#416 [FE] 마이 페이지 - 하단
  client/src/api/ChallengeAPI.ts
  client/src/api/UserAPI.ts
  client/src/components/Calendar/CalendarBody.tsx
  client/src/components/CalendarHeatMap/index.tsx
  client/src/components/FollowButton/style.ts
  client/src/components/LogoutButton/index.tsx
  client/src/components/LogoutButton/style.ts
  client/src/components/MyPageUserProfile/style.ts
  client/src/components/design/Modal/index.tsx
  client/src/components/design/Modal/style.ts
  client/src/constants/consts.ts
  client/src/hooks/query/useAllExerciseDate.ts
  client/src/hooks/query/useRecordExercise.ts
  client/src/pages/PageTemplate.tsx
  client/src/pages/ProfilePage/index.tsx
  client/src/pages/ProfilePage/style.ts
  client/src/pages/RecordPage/index.tsx
  client/src/stores/modalStore.ts
Labels: 🎨 style, ✨ feature, 🛶 frontend, ♻ refactor, ✈️ Super Pass

#419 [FE] 코어 - 예외 처리 (Toast 사용)
  client/package-lock.json
  client/package.json
  client/src/api/ChallengeAPI.ts
  client/src/api/ExerciseAPI.ts
  client/src/api/FollowAPI.ts
  client/src/api/StatisticsAPI.ts
  client/src/api/UserAPI.ts
  client/src/components/ExerciseRecordItem/ExerciseSetItem.tsx
  client/src/components/LogoutButton/index.tsx
  client/src/components/RoutineSaveButton/index.tsx
  client/src/components/RoutineSaveButton/style.ts
  client/src/components/RoutineScroller/index.tsx
  client/src/components/RoutineScroller/style.ts
  client/src/components/design/Modal/index.tsx
  client/src/components/design/Modal/style.ts
  client/src/constants/enums.ts
  client/src/constants/message.ts
  client/src/hooks/query/routine/useDeleteRoutine.ts
  client/src/hooks/query/routine/useRoutineList.ts
  client/src/hooks/query/routine/useSaveRoutine.ts
  client/src/pages/PageTemplate.tsx
  client/src/pages/RecordPage/index.tsx
  client/src/services/HttpClient.ts
  client/src/stores/modalStore.ts
  client/src/styles/Theme.ts
  client/webpack.config.js
Labels: ✨ feature, 🛶 frontend, ♻ refactor, ✈️ Super Pass

#422 [BE] API 구현 - USER API - update user 버그 수정
  server/src/domain/users/users.controller.ts
Labels: 🐛 bug, 🚀 backend

#427 [BE] test - setting - alias path 수정
  server/src/config/typeorm.config.ts
  server/src/domain/alarms/alarms.controller.ts
  server/src/domain/exercises/exercises.service.ts
  server/src/domain/oauth/google-oauth/google-oauth.module.ts
  server/src/domain/oauth/google-oauth/google-oauth.service.ts
  server/src/guard/jwt.strategy.ts
  server/src/main.ts
  server/test/app.e2e-spec.ts
  server/test/jest-e2e.json
  server/tsconfig.json
Labels: ⚙ setting, 🚀 backend, ✈️ Super Pass

#420 [FE] 알림 페이지 - 메인
  client/public/icons/btn_notification.svg
  client/src/App.tsx
  client/src/api/NotificationAPI.ts
  client/src/components/Loading/style.ts
  client/src/components/MyPageUserProfile/style.ts
  client/src/components/NotificationButton/index.tsx
  client/src/components/NotificationButton/style.ts
  client/src/components/NotificationItem/index.tsx
  client/src/components/NotificationItem/style.ts
  client/src/components/TopNavigationBar/style.ts
  client/src/constants/consts.ts
  client/src/constants/enums.ts
  client/src/constants/message.ts
  client/src/contexts/EventSourceContext.tsx
  client/src/hooks/query/notification/useNotificationCount.ts
  client/src/hooks/query/notification/useNotificationHistory.ts
  client/src/hooks/query/user/useGoogleLogin.ts
  client/src/hooks/useIntersect.ts
  client/src/hooks/useServerEvents.ts
  client/src/pages/HomePage/index.tsx
  client/src/pages/NotificationPage/index.tsx
  client/src/pages/NotificationPage/style.ts
  client/src/pages/PageTemplate.tsx
  client/src/services/Exception.ts
  client/src/styles/Components.ts
  client/src/types/notification.d.ts
  client/src/utils/getLastDateText.ts
  server/src/domain/alarms/alarms.controller.ts
  server/src/domain/alarms/alarms.service.ts
  server/src/domain/event/event.controller.ts
Labels: 🎨 style, ✨ feature, 🚀 backend, 🛶 frontend, ♻ refactor

#424 [BE] API - 3대 운동 제출시 티어 변동 구현
  server/src/domain/exercises/exercises.service.ts
  server/src/domain/sbd_records/sbd_records.service.ts
  server/src/utils/classify.ts
Labels: ✨ feature, 🚀 backend

#414 [FE] 간단한 컴포넌트 수정작업
  client/src/components/MyPageUserProfile/index.tsx
  client/src/components/SearchResultUserProfile/style.ts
  client/src/components/TierGraph/index.tsx
  client/src/components/TierGraph/mockData.ts
  client/src/pages/ProfilePage/index.tsx
  client/src/pages/SearchPage/index.tsx
  client/src/pages/SearchPage/utils.tsx
Labels: 🎨 style, ✨ feature, 🛶 frontend, ♻ refactor

#423 [FE]마이페이지 - 마이페이지 수정 - 레이아웃 / 기능 구현
  client/src/App.tsx
  client/src/api/UserAPI.ts
  client/src/components/FollowButton/index.tsx
  client/src/components/MyPageEditButton/index.tsx
  client/src/components/MyPageUserProfile/index.tsx
  client/src/components/MyPageUserProfile/style.ts
  client/src/constants/enums.ts
  client/src/pages/ProfileEditPage/index.tsx
  client/src/pages/ProfileEditPage/style.ts
  client/src/pages/ProfilePage/index.tsx
  client/src/pages/ProfilePage/style.ts
  client/src/types/user.d.ts
Labels: 🎨 style, ✨ feature, 🛶 frontend

#432 [BE] 티어 인덱스 버그 수정
  server/src/utils/classify.ts
Labels: 🐛 bug, 🚀 backend, ✈️ Super Pass

#439 [BE] DB - multer - user_profiles 로 경로 수정
  server/src/domain/users/options/multer_options.ts
  server/src/domain/users/users.service.ts
Labels: 🐛 bug, 🚀 backend, ✈️ Super Pass

#440 [BE] DB - multer - 파일 없는 요청 왔을때 예외처리
  server/src/domain/users/users.controller.ts
Labels: 🐛 bug, 🚀 backend, ✈️ Super Pass

#436 [BE] 테스팅 - USER API - Jest Test Code 작성
  server/src/app.module.ts
  server/src/config/typeorm.config.ts
  server/src/domain/event/event.controller.ts
  server/src/domain/exercises/exercises.controller.ts
  server/src/domain/oauth/google-oauth/google-oauth.controller.spec.ts
  server/src/domain/oauth/google-oauth/google-oauth.service.spec.ts
  server/src/domain/sbd_records/sbd_records.controller.ts
  server/src/domain/sbd_records/sbd_records.module.ts
  server/src/domain/sbd_records/sbd_records.service.ts
  server/test/app.e2e-spec.ts
  server/test/jest-e2e.json
  server/test/users.e2e-spec.ts
  server/tsconfig.json
Labels: 🚀 backend, 🧪 test, ✈️ Super Pass

#442 [BE] 테스팅 - RECORD API - Jest Test Code 작성
  server/test/record.e2e-spec.ts
Labels: 🚀 backend, 🧪 test, ✈️ Super Pass

#451 [FE] 페이지 애니메이션 적용
  client/src/components/ExerciseSetContainer/index.tsx
  client/src/components/ExerciseSetContainer/style.ts
  client/src/components/FollowButton/index.tsx
  client/src/components/FollowButton/style.ts
  client/src/components/MyPageUserProfile/style.ts
  client/src/components/ProfileImageContainer/style.ts
  client/src/components/SearchedUserList/style.ts
  client/src/pages/CalendarPage/style.ts
  client/src/pages/ProfileEditPage/style.ts
  client/src/styles/Theme.ts
Labels: 🎨 style, 🛶 frontend

#456 [FE] 차트버그 / 스타일링 개선
  client/src/components/ProfileImageContainer/style.ts
  client/src/components/RecommendUserCard/style.ts
  client/src/components/TierGraph/option.ts
  client/src/pages/SearchPage/index.tsx
Labels: 🐛 bug, 🎨 style, 🛶 frontend, ✈️ Super Pass

#428 [FE] 코어 - 성능 개선 - useQuery + Suspense
  .gitignore
  client/src/api/ChallengeAPI.ts
  client/src/api/ExerciseAPI.ts
  client/src/api/FollowAPI.ts
  client/src/api/UserAPI.ts
  client/src/components/CalendarHeatMap/index.tsx
  client/src/components/FollowButton/index.tsx
  client/src/components/FollowButton/style.ts
  client/src/components/MyPageUserProfile/index.tsx
  client/src/components/MyPageUserProfile/style.ts
  client/src/components/ProfileImageContainer/index.tsx
  client/src/components/RecommendUserCard/index.tsx
  client/src/components/SearchResultUserProfile/index.tsx
  client/src/components/SearchResultUserProfile/style.ts
  client/src/components/SearchedUserList/index.tsx
  client/src/components/TierGraph/index.tsx
  client/src/components/UserInfoSummary/index.tsx
  client/src/constants/enums.ts
  client/src/hooks/query/challenge/useChallengeHistory.ts
  client/src/hooks/query/follow/useFollow.ts
  client/src/hooks/query/follow/useFollowUserList.ts
  client/src/hooks/query/follow/useUnfollow.ts
  client/src/hooks/query/user/useAllUserList.ts
  client/src/hooks/query/user/useRecommendUserList.ts
  client/src/pages/FollowPage/index.tsx
  client/src/pages/FollowPage/style.ts
  client/src/pages/ProfilePage/index.tsx
  client/src/pages/SearchPage/RecommedUserList.tsx
  client/src/pages/SearchPage/index.tsx
  client/src/pages/SearchPage/styles.ts
  client/src/pages/StatisticsPage/index.tsx
  client/src/types/challenge.d.ts
  client/src/types/exercise.d.ts
  client/src/utils/SearchUtils.ts
  client/src/utils/debounce.ts
Labels: 🐛 bug, 🎨 style, 🛶 frontend, ♻ refactor

#431 [FE] 챌린지 페이지 - 티어 제공 동작 구현
  client/src/api/ChallengeAPI.ts
  client/src/components/MyPageUserProfile/index.tsx
  client/src/components/UserInfoSummary/index.tsx
  client/src/components/UserInfoSummary/style.ts
  client/src/components/design/Modal/index.tsx
  client/src/components/design/Modal/style.ts
  client/src/constants/enums.ts
  client/src/constants/message.ts
  client/src/hooks/query/challenge/useSubmitChallenge.ts
  client/src/pages/ChallengePage/index.tsx
  client/src/pages/ChallengePage/style.ts
  client/src/types/challenge.d.ts
  client/src/types/user.d.ts
Labels: 🎨 style, ✨ feature, 🛶 frontend

#435 [FE] 프로필 페이지 - 프로필 수정 개선
  client/src/api/UserAPI.ts
  client/src/constants/enums.ts
  client/src/constants/message.ts
  client/src/hooks/query/user/useUserUpdate.ts
  client/src/pages/JoinPage/index.tsx
  client/src/pages/ProfileEditPage/index.tsx
  client/src/pages/ProfileEditPage/style.ts
  client/src/types/user.d.ts
Labels: 🎨 style, ✨ feature, 🛶 frontend, ♻ refactor

#460 [BE] 테스팅 - USER API - 버그 수정
  server/test/users.e2e-spec.ts
Labels: 🐛 bug, 🚀 backend, 🧪 test, ✈️ Super Pass

#461 [BE] 테스팅 - RECORD API - 자동 종료 수정
  server/test/record.e2e-spec.ts
Labels: 🐛 bug, 🚀 backend, 🧪 test, ✈️ Super Pass

#452 [FE] 모바일 OS 판별 후 앱 설치 방법 프롬프트 띄우기
  client/src/App.tsx
  client/src/components/AppInstallPrompt/index.tsx
  client/src/components/AppInstallPrompt/style.ts
  client/src/components/MainContainer/index.tsx
  client/src/components/design/Modal/style.ts
  client/src/constants/enums.ts
  client/src/hooks/useAppInstall.ts
  client/src/services/Cookie.ts
  client/src/utils/checkIsIOS.ts
Labels: 🎨 style, ✨ feature, 🛶 frontend

#447 [BE] test - exercise 테스트 코드 파일 생성
  server/src/domain/alarms/alarms.controller.ts
  server/src/domain/alarms/alarms.service.ts
  server/src/domain/users/users.controller.ts
  server/test/exercise.e2e-spec.ts
  server/test/users.e2e-spec.ts
Labels: 🚀 backend, 🧪 test

#463 [BE] No AuthGuard 스크립트 추가
  server/package.json
  server/src/main.ts
Labels: ✨ feature, 🚀 backend

#469 [FE] 컨플릭트 해결 및 버그 해결
  client/cypress/support/commands.ts
  client/src/api/NotificationAPI.ts
  client/src/api/UserAPI.ts
  client/src/components/AppInstallPrompt/index.tsx
  client/src/components/MyPageUserProfile/style.ts
  client/src/components/ProfileImageContainer/style.ts
  client/src/components/UserInfoSummary/index.tsx
  client/src/hooks/query/user/useUserUpdate.ts
  client/src/pages/ProfileEditPage/index.tsx
  client/src/pages/ProfileEditPage/style.ts
  client/src/types/user.d.ts
Labels: 🐛 bug, 🛶 frontend, ♻ refactor, ✈️ Super Pass

#475 [FE] 로그인 페이지 - 개선
  client/public/images/screenshot-home.webp
  client/public/images/screenshot-profile.webp
  client/public/images/screenshot-search.webp
  client/public/images/screenshot-statistics.webp
  client/src/App.tsx
  client/src/components/MainContainer/index.tsx
  client/src/components/design/CardsScroller/style.ts
  client/src/pages/LoginPage/index.tsx
  client/src/pages/LoginPage/style.ts
  client/src/pages/PageTemplate.tsx
  client/src/services/Exception.ts
Labels: 🎨 style, ✨ feature, 🛶 frontend, ♻ refactor, ✈️ Super Pass

#476 [FE] 팔로우 페이지 - 팔로우 리스트 캐싱 버그 해결
  client/src/components/SearchResultUserProfile/style.ts
  client/src/components/SearchedUserList/style.ts
  client/src/hooks/query/follow/useFollowUserList.ts
Labels: 🐛 bug, 🛶 frontend, ✈️ Super Pass

#477 [FE] 코어 - PWA 빌드
  client/cypress/intergration/home.spec.ts
  client/package-lock.json
  client/package.json
  client/public/appImages/launchericon-192.png
  client/public/appImages/launchericon-512.png
  client/public/appImages/launchericon-64.png
  client/public/appImages/screenshot-home.png
  client/public/appImages/screenshot-profile.png
  client/public/appImages/screenshot-search.png
  client/public/appImages/screenshot-statistics.png
  client/public/fitory-logo.svg
  client/public/index.html
  client/public/manifest.json
  client/public/offline.html
  client/public/pwabuilder-sw.js
  client/src/components/TierGraph/index.tsx
  client/webpack.config.js
Labels: ⚙ setting, 🛶 frontend, ✈️ Super Pass

#478 [FE] - 검색 페이지 - 추천 사용자 리스트 hover 추가
  client/src/components/FollowButton/style.ts
  client/src/components/RecommendUserCard/style.ts
Labels: 🎨 style, 🛶 frontend, ✈️ Super Pass

#465 [BE] API - 자기 자신 추천 막기, 자기 자신 팔로우 막기
  server/src/domain/follows/follows.controller.ts
  server/src/domain/users/users.service.ts
Labels: 🐛 bug, 🚀 backend

#482 서버 배포 4차 - eslint 수정
  server/src/main.ts
  server/src/utils/env.ts
Labels: 🎨 style, 🚀 backend, 🚨 deploy, ✈️ Super Pass

#483 서버 배포 4차 - 가드 설정
  .github/workflows/deplol.yml
  server/src/main.ts
Labels: 🚀 backend, 🚨 deploy, ✈️ Super Pass

#484 서버 배포 4차 - pm2 process 설정
  server/src/domain/users/users.service.ts
  server/src/main.ts
  server/src/middleware/zero-downtime-deploy/graceful-shutdown.ts
  server/src/middleware/zero-downtime-deploy/is-disable-keep-alive.global.ts
  server/src/middleware/zero-downtime-deploy/set-response-header.middleware.ts
Labels: 🚀 backend, 🚨 deploy, ✈️ Super Pass

#485 서버 배포 4차 - env 경로 수정
  server/src/utils/env.ts
Labels: 🚨 deploy, ✈️ Super Pass

#486 [FE] 코어 - PWA - manifest와 service worker가 등록되지 않은 문제 해결
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/webpack.config.js
Labels: 🐛 bug, 🛶 frontend, ♻ refactor, ✈️ Super Pass

#488 [FE] 코어 - PWA - 서비스 워커 구현
  .eslintignore
  .prettierignore
  client/public/index.html
  client/public/offline.html
  client/public/pwaServiceWorker.js
  client/public/pwabuilder-sw.js
  client/webpack.config.js
Labels: ✨ feature, 🛶 frontend, ♻ refactor

#493 [FE] DB검색 최적화 프론트 작업
  client/src/api/UserAPI.ts
  client/src/pages/SearchPage/index.tsx
  client/src/utils/SearchUtils.ts
Labels: 🐛 bug, 🛶 frontend, ♻ refactor, ✈️ Super Pass

#494 [FE] 검색페이지 - 검색 - 검색어 입력 안할시 검색요청 안하게 처리
  client/src/utils/SearchUtils.ts
Labels: 🛶 frontend, ♻ refactor, ✈️ Super Pass

#495 서버 배포 4차 - DB 유저 검색 최적화
  client/package-lock.json
  client/src/api/UserAPI.ts
  client/src/pages/SearchPage/index.tsx
  client/src/utils/SearchUtils.ts
  server/src/domain/users/entities/user.entity.ts
  server/src/domain/users/users.controller.ts
  server/src/domain/users/users.service.ts
  server/test/users.e2e-spec.ts
Labels: 🚨 deploy, ✈️ Super Pass

#497 서버 배포 4차 - query select 수정
  client/src/components/SearchedUserList/index.tsx
  server/src/domain/users/users.service.ts
Labels: 🚨 deploy, ✈️ Super Pass

#499 서버 배포 4차 - 파일 경로 수정
  server/src/domain/users/users.service.ts
Labels: 🚨 deploy, ✈️ Super Pass

#500 FE] 코어 - PWA - 배포 후 나타나는 문제 해결
  client/public/index.html
  client/public/manifest.json
  client/src/components/AppInstallPrompt/index.tsx
  client/src/components/AppInstallPrompt/style.ts
  client/src/components/BottomNavigationBar/style.ts
  client/src/components/MainContainer/style.ts
  client/src/components/TopNavigationBar/style.ts
  client/src/pages/HomePage/style.ts
  client/src/styles/Theme.ts
  client/src/utils/getPWADisplayMode.ts
Labels: 🐛 bug, 🛶 frontend, ✈️ Super Pass

#501 [FE] 코어 - PWA - input 클릭시 확대되는 현상 해결
  client/public/index.html
Labels: 🐛 bug, 🛶 frontend

#502 서버 배포 4차 - PWA 수정
  client/public/index.html
  client/public/manifest.json
  client/src/components/AppInstallPrompt/index.tsx
  client/src/components/AppInstallPrompt/style.ts
  client/src/components/BottomNavigationBar/style.ts
  client/src/components/MainContainer/style.ts
  client/src/components/TopNavigationBar/style.ts
  client/src/pages/HomePage/style.ts
  client/src/styles/Theme.ts
  client/src/utils/getPWADisplayMode.ts
Labels: 🚨 deploy, ✈️ Super Pass

#467 [BE] - DB - 읽기 성능 테스트 코드 작성
  server/jest-e2e.json
  server/k6/cpu-test.js
  server/k6/db-read-test.js
  server/k6/db-write-test.js
  server/package.json
  server/test/jest-e2e.json
Labels: 🚀 backend, 🧪 test

#503 [FE] 코어 - PWA - 배포 후 나타나는 문제 해결 3
  client/.eslintrc.json
  client/public/appImages/launchericon-192-maskable.png
  client/public/appImages/launchericon-512-maskable.png
  client/public/appImages/screenshot-home.png
  client/public/appImages/screenshot-home.webp
  client/public/appImages/screenshot-profile.png
  client/public/appImages/screenshot-profile.webp
  client/public/appImages/screenshot-search.png
  client/public/appImages/screenshot-search.webp
  client/public/appImages/screenshot-statistics.png
  client/public/appImages/screenshot-statistics.webp
  client/public/manifest.json
  client/src/pages/LoginPage/index.tsx
  client/src/pages/PageTemplate.tsx
Labels: 🐛 bug, ⚙ setting, 🎨 style, 🛶 frontend, ✈️ Super Pass

#504 서버 배포 4차 - PWA 문제 해결
  README.md
  client/.eslintrc.json
  client/public/appImages/launchericon-192-maskable.png
  client/public/appImages/launchericon-512-maskable.png
  client/public/appImages/screenshot-home.webp
  client/public/appImages/screenshot-profile.webp
  client/public/appImages/screenshot-search.webp
  client/public/appImages/screenshot-statistics.webp
  client/public/manifest.json
  client/src/pages/LoginPage/index.tsx
  client/src/pages/PageTemplate.tsx
  server/jest-e2e.json
  server/k6/cpu-test.js
  server/k6/db-read-test.js
  server/k6/db-write-test.js
  server/package.json
  server/test/jest-e2e.json
Labels: 🚨 deploy, ✈️ Super Pass

#506 [BE] API 구현 - STATISTICS API - 통계 데이터 API 최적화
  server/k6/cpu-test.js
  server/src/domain/sbd_statistics/sbd_statistics.service.ts
Labels: 🐛 bug, 🚀 backend

#480 [BE] Test - Routine 테스트 코드 작성
  server/test/routine.e2e-spec.ts
Labels: 🚀 backend, 🧪 test

#507 [BE] DB - TypeORM entity index 추가
  client/src/components/TierGraph/plugin.ts
  client/src/pages/SearchPage/index.tsx
  client/src/types/challenge.d.ts
  server/src/domain/sbd_statistics/entities/sbd_statistics.entity.ts
  server/src/domain/users/entities/user.entity.ts
Labels: 🚀 backend, ♻ refactor

#514 [FE] 각종 버그 해결
  client/.eslintrc.js
  client/.eslintrc.json
  client/public/appImages/favicon.ico
  client/public/appImages/launchericon-192-maskable.png
  client/public/appImages/launchericon-192.png
  client/public/appImages/launchericon-512-maskable.png
  client/public/appImages/launchericon-512.png
  client/public/index.html
  client/src/App.tsx
  client/src/components/AppInstallPrompt/index.tsx
  client/src/components/BottomNavigationBar/style.ts
  client/src/components/Calendar/CalendarBody.tsx
  client/src/components/Calendar/CalendarElement.tsx
  client/src/components/Loading/index.tsx
  client/src/components/MainContainer/style.ts
  client/src/components/NotificationItem/style.ts
  client/src/constants/message.ts
  client/src/hooks/query/challenge/useSubmitChallenge.ts
  client/src/pages/CalendarPage/index.tsx
  client/src/pages/HomePage/style.ts
  client/src/pages/JoinPage/index.tsx
  client/src/pages/PageTemplate.tsx
  client/src/pages/ProfileEditPage/index.tsx
  client/src/pages/ProfilePage/index.tsx
  client/src/pages/SearchPage/RecommedUserList.tsx
  client/src/pages/SearchPage/index.tsx
  client/src/pages/SearchPage/styles.ts
  client/src/pages/StatisticsPage/index.tsx
  client/src/styles/Theme.ts
  client/src/utils/checkIsPWADisplayMode.ts
  client/tsconfig.json
  client/webpack.config.js
Labels: 🐛 bug, 🎨 style, 🛶 frontend, ♻ refactor, ✈️ Super Pass

#515 서버 배포 4차 - FE 각종 버그 해결에 대한 배포
  client/.eslintrc.js
  client/.eslintrc.json
  client/public/appImages/favicon.ico
  client/public/appImages/launchericon-192-maskable.png
  client/public/appImages/launchericon-192.png
  client/public/appImages/launchericon-512-maskable.png
  client/public/appImages/launchericon-512.png
  client/public/index.html
  client/src/App.tsx
  client/src/components/AppInstallPrompt/index.tsx
  client/src/components/BottomNavigationBar/style.ts
  client/src/components/Calendar/CalendarBody.tsx
  client/src/components/Calendar/CalendarElement.tsx
  client/src/components/Loading/index.tsx
  client/src/components/MainContainer/style.ts
  client/src/components/NotificationItem/style.ts
  client/src/components/TierGraph/plugin.ts
  client/src/constants/message.ts
  client/src/hooks/query/challenge/useSubmitChallenge.ts
  client/src/pages/CalendarPage/index.tsx
  client/src/pages/HomePage/style.ts
  client/src/pages/JoinPage/index.tsx
  client/src/pages/PageTemplate.tsx
  client/src/pages/ProfileEditPage/index.tsx
  client/src/pages/ProfilePage/index.tsx
  client/src/pages/SearchPage/RecommedUserList.tsx
  client/src/pages/SearchPage/index.tsx
  client/src/pages/SearchPage/styles.ts
  client/src/pages/StatisticsPage/index.tsx
  client/src/styles/Theme.ts
  client/src/types/challenge.d.ts
  client/src/utils/SearchUtils.ts
  client/src/utils/checkIsPWADisplayMode.ts
  client/tsconfig.json
  client/webpack.config.js
  server/jest-e2e.json
  server/k6/cpu-test.js
  server/src/domain/sbd_statistics/entities/sbd_statistics.entity.ts
  server/src/domain/users/entities/user.entity.ts
  server/src/domain/users/users.service.ts
  server/src/main.ts
  server/test/routine.e2e-spec.ts
  server/test/users.e2e-spec.ts
Labels: 🚨 deploy, ✈️ Super Pass

#520 [BE] DB - entity index name 설정
  server/src/domain/sbd_statistics/entities/sbd_statistics.entity.ts
  server/src/domain/sbd_statistics/sbd_statistics.service.ts
  server/src/domain/users/entities/user.entity.ts
  server/src/domain/users/users.service.ts
Labels: 🚀 backend, 🛶 frontend, ✈️ Super Pass

#521 [BE] DB - user 테이블에 follow 관련 컬럼 추가
  server/src/domain/alarms/alarms.controller.ts
  server/src/domain/alarms/alarms.service.ts
  server/src/domain/follows/follows.service.ts
  server/src/domain/oauth/google-oauth/google-oauth.controller.ts
  server/src/domain/users/entities/user.entity.ts
  server/src/main.ts
Labels: 🚀 backend, ♻ refactor, ✈️ Super Pass

#522 [BE] DB - multi index 설정
  server/src/domain/sbd_statistics/entities/sbd_statistics.entity.ts
Labels: 🚀 backend

#519 [FE] 컴포넌트 디렉토리 분리
  client/src/App.tsx
  client/src/common/design/BackButton/index.tsx
  client/src/common/design/BackButton/style.ts
  client/src/common/design/CardsScroller/index.tsx
  client/src/common/design/CardsScroller/style.ts
  client/src/common/design/Modal/index.tsx
  client/src/common/design/Modal/style.ts
  client/src/common/design/Paper/index.tsx
  client/src/common/design/Paper/style.ts
  client/src/common/design/ProfileImageContainer/index.tsx
  client/src/common/design/ProfileImageContainer/style.ts
  client/src/common/layer/BottomNavigationBar/BottomNavigationButton.tsx
  client/src/common/layer/BottomNavigationBar/index.tsx
  client/src/common/layer/BottomNavigationBar/style.ts
  client/src/common/layer/ErrorFallback/index.tsx
  client/src/common/layer/ErrorFallback/style.ts
  client/src/common/layer/Loading/index.tsx
  client/src/common/layer/Loading/style.ts
  client/src/common/layer/MainContainer/index.tsx
  client/src/common/layer/MainContainer/style.ts
  client/src/common/layer/TopNavigationBar/index.tsx
  client/src/common/layer/TopNavigationBar/style.ts
  client/src/components/AppInstallPrompt/index.tsx
  client/src/components/BottomNavigationButton/style.ts
  client/src/components/Calendar/index.tsx
  client/src/components/CalendarHeatMap/index.tsx
  client/src/components/ChallengeItem/index.tsx
  client/src/components/ExerciseSetContainer/index.tsx
  client/src/components/LogoutButton/index.tsx
  client/src/components/MyPageUserProfile/index.tsx
  client/src/components/RecommendUserCard/index.tsx
  client/src/components/RecommendUserCard/style.ts
  client/src/components/RoutineSaveButton/index.tsx
  client/src/components/RoutineScroller/index.tsx
  client/src/components/SearchResultUserProfile/index.tsx
  client/src/components/UserInfoSummary/index.tsx
  client/src/pages/ChallengePage/index.tsx
  client/src/pages/LoginPage/index.tsx
  client/src/pages/NotFountPage/index.tsx
  client/src/pages/PageTemplate.tsx
  client/src/pages/ProfileEditPage/index.tsx
  client/src/pages/SearchPage/RecommedUserList.tsx
  client/src/pages/SearchPage/styles.ts
  client/src/stories/BottomNavigationBar.stories.tsx
  client/src/stories/CardsScroller.stories.tsx
  client/src/stories/Modal.stories.tsx
  client/src/stories/Paper.stories.tsx
  client/src/stories/ProfileImageContainer.stories.tsx
  client/src/stories/TopNavigationBar.stories.tsx
  client/tsconfig.json
Labels: ⚙ setting, 🛶 frontend, ♻ refactor, ✈️ Super Pass

#524 [FE] 프로필 페이지 버그 해결 & 로고 변경
  client/public/appImages/launchericon-192-maskable.png
  client/public/appImages/launchericon-192.png
  client/public/appImages/launchericon-192.svg
  client/public/appImages/launchericon-512-maskable.png
  client/public/appImages/launchericon-512.png
  client/public/appImages/launchericon-512.svg
  client/public/favicon.ico
  client/public/fitory-logo.svg
  client/public/index.html
  client/public/manifest.json
  client/public/offline.html
  client/public/pwabuilder-sw.js
  client/src/components/FollowButton/style.ts
  client/src/components/MyPageUserProfile/index.tsx
  client/src/components/RoutineScroller/style.ts
  client/src/pages/ProfileEditPage/index.tsx
  client/src/pages/ProfilePage/index.tsx
  client/webpack.config.js
Labels: 🐛 bug, ⚙ setting, 🎨 style, 🛶 frontend, ♻ refactor, ✈️ Super Pass

#513 [BE] API 구현 - RECORD API - 통계에 반영 안되던 버그 수정
  server/src/domain/sbd_records/sbd_records.module.ts
  server/src/domain/sbd_records/sbd_records.service.ts
  server/src/domain/users/users.service.ts
Labels: 🐛 bug, 🚀 backend

#517 [BE] API 구현 - Statistics API - 반환값 오류 수정
  server/src/domain/sbd_statistics/sbd_statistics.service.ts
Labels: 🐛 bug, 🚀 backend

#526 [BE] DB - Trigger 적용으로 인해 Get User Info API에 팔로워 가져오기 삭제
  server/src/domain/users/users.controller.ts
  server/src/domain/users/users.service.ts
Labels: ✨ feature, 🚀 backend, ✈️ Super Pass

#529 [FE] 배포에 로고 적용 이슈 해결
  client/public/appImages/launchericon-64.png
  client/public/appImages/screenshot-home.png
  client/public/appImages/screenshot-profile.png
  client/public/appImages/screenshot-search.png
  client/public/appImages/screenshot-statistics.png
  client/public/index.html
  client/public/manifest.json
  client/public/pwaServiceWorker.js
  client/src/components/TierGraph/index.tsx
  client/src/components/TierGraph/plugin.ts
  client/src/components/TierGraph/style.ts
  client/src/stories/BottomNavigationBar.stories.tsx
Labels: 🐛 bug, ⚙ setting, 🎨 style, 🛶 frontend, ✈️ Super Pass

#530 서버 배포 4차 - 로고 이슈 해결
  server/src/domain/users/users.service.ts
  server/src/main.ts
Labels: 🚨 deploy, ✈️ Super Pass

#531 서버 배포 4차 - 로고 이슈 해결
  client/public/appImages/launchericon-64.png
  client/public/appImages/screenshot-home.png
  client/public/appImages/screenshot-profile.png
  client/public/appImages/screenshot-search.png
  client/public/appImages/screenshot-statistics.png
  client/public/index.html
  client/public/manifest.json
  client/public/pwaServiceWorker.js
  client/src/components/TierGraph/index.tsx
  client/src/components/TierGraph/plugin.ts
  client/src/components/TierGraph/style.ts
  client/src/stories/BottomNavigationBar.stories.tsx
Labels: 🚨 deploy, ✈️ Super Pass

#532 [FE] - 로고 되돌리기
  client/public/appImages/launchericon-192.png
  client/public/appImages/launchericon-192.svg
  client/public/appImages/launchericon-512.png
  client/public/appImages/launchericon-512.svg
  client/public/index.html
  client/public/manifest.json
  client/public/pwaServiceWorker.js
Labels: ⚙ setting, 🛶 frontend, ✈️ Super Pass

#533 서버 배포 4차 - 로고 되돌리기
  client/public/appImages/launchericon-192.png
  client/public/appImages/launchericon-192.svg
  client/public/appImages/launchericon-512.png
  client/public/appImages/launchericon-512.svg
  client/public/index.html
  client/public/manifest.json
  client/public/pwaServiceWorker.js
Labels: 🚨 deploy, ✈️ Super Pass

#535 [FE] favicon 403 에러 해결
  client/webpack.config.js
Labels: 🐛 bug, 🛶 frontend, ✈️ Super Pass

#540 [FE] 테스트 - 홈 페이지
  .eslintignore
  client/.eslintrc.js
  client/cypress.config.js
  client/cypress.config.ts
  client/cypress/fixtures/bestChallenge.json
  client/cypress/fixtures/example.json
  client/cypress/fixtures/user.json
  client/cypress/integration/home.spec.ts
  client/cypress/intergration/home.spec.ts
  client/cypress/plugins/index.js
  client/cypress/support/commands.ts
  client/cypress/support/e2e.ts
  client/cypress/tsconfig.json
  client/package-lock.json
  client/package.json
  client/src/components/Calendar/index.tsx
  client/src/components/CalendarHeatMap/index.tsx
  client/src/components/UserInfoSummary/index.tsx
  client/src/pages/LoginPage/index.tsx
Labels: 🛶 frontend, 🧪 test

#542 [FE] 서비스 워커 에러 해결
  client/public/pwaServiceWorker.js
Labels: 🐛 bug, 🛶 frontend, ✈️ Super Pass

#543 [BE] DB - entity 이름 수정
  server/src/domain/users/entities/user.entity.ts
  server/src/domain/users/users.service.ts
Labels: 🐛 bug, 🚀 backend

#548 [FE] PWA - 앱 로고 변경
  client/package.json
  client/public/appImages/launchericon-192-maskable.png
  client/public/appImages/launchericon-192.png
  client/public/appImages/launchericon-512-maskable.png
  client/public/appImages/launchericon-512.png
  client/public/favicon.ico
  client/public/index.html
Labels: ⚙ setting, 🛶 frontend

#550 [FE] favicon, 서비스 워커 에러 해결
  client/public/appImages/favicon.ico
  client/public/index.html
  client/public/pwaServiceWorker.js
  client/webpack.config.js
Labels: 🐛 bug, ⚙ setting, 🛶 frontend

#554 서버 배포 - main.ts 수정
  server/src/main.ts
Labels: 🐛 bug, 🚨 deploy

#555 서버 배포 - 통계 데이터 API typeorm 수정
  server/src/domain/sbd_statistics/sbd_statistics.service.ts
Labels: 🐛 bug, 🚨 deploy

#556 서버 배포 - 3대 챌린지 예외 처리
  server/k6/cpu-test.js
  server/src/domain/sbd_records/sbd_records.controller.ts
Labels: 🐛 bug, 🚨 deploy

#557 [BE] Refactor - 개발환경 배포환경 호환성 설정
  server/src/domain/users/users.service.ts
  server/src/main.ts
  server/src/utils/env.ts
Labels: 🚀 backend, ♻ refactor
